### ISSUE TITLE
Several minor issues with creating channels, making them public

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#106]
https://rumblefishdev.atlassian.net/browse/ZBAY-854

pasting here as a reference:

* Hyphens are currently not allowed in public channel names. Single hyphens between words should be allowed. 
* When user is publishing a channel the field should work the same as the private channel name creation field does. (see screenshot)
* Private channel creation should not have a description field
* Private channel creation screen title should be “Create a new private channel” (add the word “private”)
* placeholder text in “channel name” field on the private channel creation screen should be: e.g. "my-channel"
* When you are publishing a channel, the existing name you have chosen for the private channel should be pre-filled in the field and show a warning if it is already in use. 
* Channel creation button should show true fee in USD, like we do for messages (see screenshot). I don’t think we need to say “USD” here, actually. I think the dollar sign is enough.
* In both channel name fields (private and public) the “Your channel will be created as…” message should only show if the user has used a space that we are replacing with a hyphen. 
* You should only be able to use a single hyphen in a row, not a large row of hyphens. 
* text and warning icon should display in-line when there is a long channel name. 
* Text below “make channel public” button should say “Registering a public channel may cost more someday, but now it's (almost) free.”

**Comment by NorbertBodziony** [comment]
fix in #117

**Comment by NorbertBodziony** [comment]
Fixed in #101.

**Comment by holmesworcester** [comment]
@danielcybulka just flagging that there are quite a lot of small changes here so QA in this area will be helpful!

**Comment by danielcybulka** [comment]
> Channel creation button should show true fee in USD, like we do for messages (see screenshot). I don’t think we need to say “USD” here, actually. I think the dollar sign is enough.
@holmesworcester Publishing button is acceptable assuming that we are comfortable with 0.0000 precision (on screenshot from jira I saw 0.00001). Only publishing button has info about price, that's why I thought creating private channel is free until Janusz told me it isn't. I think we should add similar price info on button during private channel creation as well.

**Comment by danielcybulka** [comment]
On mac and windows in channel name only multiple spaces are converted to hypens, single space is allowed. Reopening the issue

**Comment by NorbertBodziony** [comment]
Just to clarify. If user types hyphens by himself he can use multiple in a row ? @holmesworcester

**Comment by NorbertBodziony** [comment]
#156

**Comment by holmesworcester** [comment]
> Just to clarify. If user types hyphens by himself he can use multiple in a row ? @holmesworcester

no, i don't think so. i think we want to enforce uniformly-formatted channel names for design reasons and to avoid user confusion about what channel they are joining or sending a message to.

**Comment by NorbertBodziony** [comment]
Adjusted #156

**Comment by danielcybulka** [comment]
@holmesworcester 
Right now only one hypen is allowed which means:
- only one space is allowed in entire channel name,
- only one hyphen is allowed in entire channel name,
- hyphen can't be the first or last character in channel name.

If this is what we wanted then issue is fixed.

**Comment by holmesworcester** [comment]
you should be able to have a channel such as "my-long-channel-name" but not "------my channel------"

**Comment by holmesworcester** [comment]
created new ticket #202
