### ISSUE TITLE
Zbay dies on hibernate then fails to connect on restart

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#111]
https://rumblefishdev.atlassian.net/browse/ZBAY-915

**Comment by jkdev601** [comment]
Fix in #146

**Comment by danielcybulka** [comment]
@holmesworcester I wasn't able to reproduce this bug. Both on mac and windows after waking up, app has 2-3 failed http requests and after that everything is getting back to normal. I will try more once I'm done with rest of the tests.

**Comment by holmesworcester** [comment]
this is great. i think this ticket existed because there was an issue in the past.

**Comment by jkdev601** [comment]
@holmesworcester this happened once on our mac (phantom zcashd), there is separate mechanism introduced to detect and fix this state while you still running Zbay with phantom zcashd after wake up without restart.

**Comment by holmesworcester** [comment]
okay, so we think this is due to a phantom zcashd?

**Comment by SzymonJaworskiRF** [comment]
#198 I closed this issue here. @holmesworcester do you think we should close this one as well?

**Comment by SzymonJaworskiRF** [comment]
After hibernate zbay shows incorrect amount of money on windows. @jkdev601 seen that.

![image](https://user-images.githubusercontent.com/67907892/86910948-554b8f80-c0cf-11ea-9ae5-dc8b7e52ca53.png)

**Comment by holmesworcester** [comment]
Let's make a new ticket for this. It sounds like the original issue is solved.

**Comment by holmesworcester** [comment]
@SzymonJaworskiRF in the screenshot it looks like your message didn't go through. should that be another ticket?

**Comment by SzymonJaworskiRF** [comment]
After talking with @jkdev601 I think the issue #272 is enough because problem with sending messages there is probably related to displaying incorrect balance.

**Comment by holmesworcester** [comment]
okay, closing this as a duplicate.
