### ISSUE TITLE
If another zcashd is running when Zbay starts up, zbay should kill it

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#112]
https://rumblefishdev.atlassian.net/browse/ZBAY-916

**Comment by jkdev601** [comment]
Fix in #146

**Comment by danielcybulka** [comment]
Works fine on Mac.

On windows there are two scenarios:
1. Running zcashd.exe when Zbay is alive doesn't terminate Zbay's zcashd.exe
2. Running Zbay when zcashd.exe is already running terminates existing zcashd.exe but also new instance is NOT created for Zbay.

@jkdev601 mentioned that after 3 minutes zcashd.exe will be created eventually but will force files rescan.

**Comment by holmesworcester** [comment]
this seems right to me, as long as a new zcashd is created in case #2.

**Comment by holmesworcester** [comment]
note: only blocks windows release

**Comment by holmesworcester** [comment]
Making this non blocking because devs can't reproduce, but we should investigate and fix.

**Comment by holmesworcester** [comment]
removing from backlog since we can't reproduce it and it's solved by light client
