### ISSUE TITLE
Radio button labels should be clickable

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#120]
On "send funds" screen, the radio buttons are clickable but the Yes/No labels are not. 

Steps to reproduce: click "send funds" in sidebar, click "yes" and "no"

Expected: the radio buttons toggle respective to label clicked

Actual: nothing happens

**Comment by holmesworcester** [comment]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/213678/84922777-57a06800-b094-11ea-909c-737838df3285.png">

**Comment by NorbertBodziony** [comment]
Patched in PR #144.
