### ISSUE TITLE
Opening "private address" section should scroll down to show contents

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#121]
Right now if you open the "private address" section on the "Add funds" page it's hard to tell that anything happened. 

Clicking that section should scroll the page down to show the contents of that section.

**Comment by danielcybulka** [comment]
After copying the private address few times with touchpad I would love to see 'Copy address to clipboard' button as it is below transparent address.

**Comment by NorbertBodziony** [comment]
@holmesworcester should we include @danielcybulka suggestion ?

**Comment by NorbertBodziony** [comment]
Scroll added in #145

**Comment by holmesworcester** [comment]
> @holmesworcester should we include @danielcybulka suggestion ?

Yes, that's a good idea. I created a ticket. https://github.com/ZbayApp/zbay/issues/149
