### ISSUE TITLE
Shipping address country should auto-detect locale

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#123]
The default country should be the detected locale, until user changes it. Fall back to "United States" if not detected, since many of the user's we're testing with initially are in the US.

**Comment by NorbertBodziony** [comment]
#147

**Comment by danielcybulka** [comment]
Works on 'Buy Zcash' instructions but new user still got empty field.

@holmesworcester I'm not sure if any field of shipping address should be autofilled. This app is all about privacy and when new user is setting his address the first thing he/she sees is autofilled country which is taken from...? We know it's from OS but less technical user might get second thoughts about it. It's very small utility and I don't think it's worth it. Maybe I'm being silly but this is how I see it.

**Comment by holmesworcester** [comment]
Hm. The data is only shared when the user ships something to themselves, and they would still have to enter their other address details in order to have an address that validates, no? As long as there isn’t a way to accidentally submit your country to a seller without entering the rest of your address, this seems okay.

If we autodetect it we can put “region" before “country” in the form, which is more natural for entering an address. It’s also helpful on the “buy zcash” page so that we can show the correct option for buying.
