### ISSUE TITLE
Scrollbar overlaps content of channel settings

### ISSUE THREAD

**Issue by danielcybulka** [ZbayApp/zbay#129]
Version: 1.0.68-dev-test-windows-2, 1.0.68-dev-test-mac-version-2
Platform: Windows 10 x64, Mac OS X
zcashd: v2.1.2

Steps to reproduce:
1. Open any channel which you can edit.
2. Open its settings and select 'Channel info'.
3. Shrink the window so the scrollbar appears on the settings content. Scrollbar will overlap the content instead of being next to it.

![Scrollbar overlap](https://user-images.githubusercontent.com/67123884/85070656-77c84800-b1b6-11ea-8dbb-8a2ddf86ec5d.PNG)

**Comment by jkdev601** [comment]
Fix in #236
