### ISSUE TITLE
USD to ZEC calculation is not working during offer purchase under $1

### ISSUE THREAD

**Issue by danielcybulka** [ZbayApp/zbay#133]
Version: 1.0.68-dev-test-windows-2, 1.0.68-dev-test-mac-2, 
Platform: Windows 10 x64, Mac OS X
zcashd: v2.1.2

Steps to reproduce:
1. Click 'buy' on any offer,
2. On 'Send Funds' screen, Amount to Send always show
 0.0000 ZEC on small amounts (not sure about exact amount but will be probably below $0.5)

![offer amount bug](https://user-images.githubusercontent.com/67123884/85134002-11860880-b23c-11ea-861a-7d28236db27e.PNG)

For $1 it was calculated correctly:
![correct calculation offer](https://user-images.githubusercontent.com/67123884/85134189-6164cf80-b23c-11ea-87ee-94cdf2bd1ff6.PNG)

**Comment by NorbertBodziony** [comment]
![image](https://user-images.githubusercontent.com/38857779/85537357-2f74b400-b614-11ea-9750-d0f7b28b4adb.png)
I will also change front view of advert to show 4 decimal places since front view also shows 0.00 ZEC.

**Comment by danielcybulka** [comment]
This fix will be available in next build right?

**Comment by NorbertBodziony** [comment]
Yes i will.
