### ISSUE TITLE
Error after every offer purchase

### ISSUE THREAD

**Issue by danielcybulka** [ZbayApp/zbay#134]
Version: 1.0.68-dev-test-windows-2, 1.0.68-dev-test-mac-2,
Platform: Windows 10 x64, Mac OS X
zcashd: v2.1.2

After every purchase such message appears:
![offer notification bug](https://user-images.githubusercontent.com/67123884/85134542-f7005f00-b23c-11ea-8f01-a8a603a9e262.PNG)

'Unknown' user turns lafter few seconds to correct username.

At first glance nothing bad happened but I would be quite anxious seeing such message after paying lots of $.

UPDATE: This message occurs also (or maybe mainly) when messaging the offerer/buyer.

**Comment by NorbertBodziony** [comment]
Related #158

**Comment by danielcybulka** [comment]
> Related #158

Indeed, it works fine after fix related to #158 . Closing the issue
