### ISSUE TITLE
Address validation during offer purchase should be displayed earlier

### ISSUE THREAD

**Issue by danielcybulka** [ZbayApp/zbay#135]
Version: 1.0.68-dev-test-windows-2, 1.0.68-dev-test-mac-2,
Platform: Windows 10 x64, Mac OS X
zcashd: v2.1.2

Steps to reproduce:
1. Buy an offer with requires including address
2. On 'Send Funds' screen by default 'Include shipping address' is unchecked and 'Send Funds' button is disabled. 
3. After checking and unchecking the option, validation message is displayed 'You have to provide shipping information'.

In my opinion this message should appear right after entering 'Send Funds' screen or at least after trying to press 'Send Funds' button.

**Comment by holmesworcester** [comment]
@danielcybulka what if it's selected by default when shipping address required, and the button says "Send funds & shipping address." Thoughts on this?

**Comment by danielcybulka** [comment]
@holmesworcester I think in terms of privacy it's better that user needs to check it. I find it somehow similar to Terms of Agreement checkboxes - it's forbidden to check them by default to make sure that user actually wants it and it's not just a miss click.

**Comment by holmesworcester** [comment]
ok so let’s show error immediately then, if address is required.

**Comment by NorbertBodziony** [comment]
#253
