### ISSUE TITLE
@Mentions are not triggering notifications

### ISSUE THREAD

**Issue by danielcybulka** [ZbayApp/zbay#139]
Version: 1.0.68-dev-test-windows-2, 1.0.68-dev-test-mac-2,
Platform: Windows 10 x64, Mac OS X
zcashd: v2.1.2

Mentioning someone in DM or private/public is not triggering notification. 
I'm not sure how it should work but I guess that system popup should come out when e.g. someone mentions me on the public channel.

**Comment by NorbertBodziony** [comment]
#250

**Comment by SzymonJaworskiRF** [comment]
Still needs fixing.

**Comment by NorbertBodziony** [comment]
I need more details main feature seems to be fine.

**Comment by holmesworcester** [comment]
@SzymonJaworskiRF can you provide norbert with clear steps to reproduce and confirm that he can?

**Comment by holmesworcester** [comment]
@SzymonJaworskiRF were you able to provide steps to norbert so that he can reproduce this?

**Comment by NorbertBodziony** [comment]
Fixed. User settings still act as superior to channel settings.
