### ISSUE TITLE
Users should see a website that is not a wall of text :) 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#153]
Here's a webflow: https://zbay-v2.webflow.io/

Webflow export follows, in case it's helpful:
[zbay-v2.webflow (1).zip](https://github.com/ZbayApp/zbay/files/4823419/zbay-v2.webflow.1.zip)

Notes: 
* Existing site copy should be preserved wherever possible. That is, the "How it works", "Why" and "FAQ" pages should use the latest content on the site and not the content in this webflow, which should be treated as a mockup.
* All the new text on the homepage is real
* No content should load from webflow's servers.
* Existing prompt to download zbay for invitation links should still work.

**Comment by NorbertBodziony** [comment]
I think it's done ? @holmesworcester

**Comment by holmesworcester** [comment]
Yep. Closing.
