### ISSUE TITLE
Purchases crash the app

### ISSUE THREAD

**Issue by danielcybulka** [ZbayApp/zbay#158]
Mac & Windows: 1.0.68-dev-test

Steps to reproduce:
1. Click 'Buy' on any offer
2. On 'Send Funds' screen click 'Send Funds' button (agree to show address if necessary).
3. UI dissappears, app window is all white. Console says:
Windows:
![purchase error](https://user-images.githubusercontent.com/67123884/85586119-ebe46f00-b640-11ea-802d-563842d33255.PNG)

Mac:
![Zrzut ekranu 2020-06-24 o 07 51 57](https://user-images.githubusercontent.com/67123884/85586810-152bdd80-b5f6-11ea-8470-47d889e448dd.png)

**Comment by danielcybulka** [comment]
Update: Same thing happends when entering DM thread created during purchase.

**Comment by NorbertBodziony** [comment]
Problem is that we try to do these operations before offer is posted into the network.(We interact with ourselves) We create flow of communication on offer based on real transaction which we don't have since its still pending. I propose we disable interaction with our offers or postpone it until transaction is posted into the network. @holmesworcester @jkdev601

**Comment by NorbertBodziony** [comment]
@danielcybulka can you confirm that it only occurs on offers that you post before confirmation (double checkmark)?

**Comment by danielcybulka** [comment]
@NorbertBodziony That's correct. I just found that same problem occurs when I'm trying to open old DM's created by buying offers in the past. I can't even remove because just clicking them crashes the app.

**Comment by danielcybulka** [comment]
> @NorbertBodziony That's correct. I just found that same problem occurs when I'm trying to open old DM's created by buying offers in the past. I can't even remove them because just clicking them crashes the app.

I was wrong. It worked when offer is purchased by the user who created the offer. All other scenarios still crash the app.

**Comment by holmesworcester** [comment]
> Problem is that we try to do these operations before offer is posted into the network.(We interact with ourselves) We create flow of communication on offer based on real transaction which we don't have since its still pending. I propose we disable interaction with our offers or postpone it until transaction is posted into the network. @holmesworcester @jkdev601

@NorbertBodziony so the proposal is: "Message button does not display until offer is posted to network." Is that correct?

**Comment by NorbertBodziony** [comment]
Yes maybe even block entire modal of offer.

**Comment by holmesworcester** [comment]
i think blocking the modal might be uncomfortable or confusing. people just posted something and might want to see it.

**Comment by NorbertBodziony** [comment]
Ok so just block buttons.

**Comment by holmesworcester** [comment]
great, and this will only appear to the user who has created the item, right?

**Comment by NorbertBodziony** [comment]
Yes thats right.

**Comment by NorbertBodziony** [comment]
PR #169

**Comment by danielcybulka** [comment]
Mac 1.0.74

Clicking a button that publishes new offer triggers spinner, but after a while app crashes. Logs from mac:
![Zrzut ekranu 2020-06-30 o 02 24 36](https://user-images.githubusercontent.com/67123884/86109574-5f3f1400-ba79-11ea-9738-e742dbdfecba.png)

**Comment by danielcybulka** [comment]
I tested the main issue and it seems to be fixed so I'm closing this thread. Validation error and crash are continued in #199
