### ISSUE TITLE
User is not warned when opening links

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#160]
Steps to reproduce:

1. Receive a link in a DM to a non-whitelisted site.
2. Click link

Expected: warning displays about following external links, unless whitelisted.
Actual: no warning displays, for any links.

If there is any automated testing that we can put in place to protect against regressions here, it's worth putting in that effort now.

**Comment by danielcybulka** [comment]
Can't reproduce both on Mac and Windows, works just fine.

**Comment by jkdev601** [comment]
@holmesworcester, try to check security tab in settings maybe 'Never warn me about outbound link on Zbay' is enabled.

**Comment by holmesworcester** [comment]
ugh, my mistake, it was.

**Comment by holmesworcester** [comment]
invalid
