### ISSUE TITLE
Impossible to deselect "Don't warn me" on outbound links warning

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#164]
Scenario: user clicks "don't warn me about links.com again" but then changes her mind before continuing and actually would like to be warned.

User cannot deselect "don't warn me..." without selecting "never warn me..."

Proposed solution: these should be checkboxes and not radio buttons. If both are checked, then the "never warn" gets turned on *and* the site gets added to the whitelist. That way, if user turns off "never warn" the site is still whitelisted. 

Also, the checkbox label text, e.g. "don't warn me...", should be clickable to toggle the checkbox.

(I think it used to work this way and the problem might have been a mistake in a previous instruction or ticket? ) 

<img width="999" alt="image" src="https://user-images.githubusercontent.com/213678/85712955-dad64500-b6b6-11ea-8844-96874d51ba2f.png">

**Comment by NorbertBodziony** [comment]
Yes exactly it worked like that. Similar issue with opening images. Should i just revert these changes ? @holmesworcester

**Comment by holmesworcester** [comment]
ugh, sorry about that! okay, yes, please revert!

**Comment by NorbertBodziony** [comment]
PR #172
