### ISSUE TITLE
On Windows, invitation link only opens if Zbay is open

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#165]
In #131 our fix for Windows only works if Zbay is open. It should work even if Zbay is not open.

It should be possible at the OS level but it's unclear to me whether Electron makes it possible:

* https://stackoverflow.com/questions/5006486/how-can-i-launch-my-windows-app-when-a-users-opens-a-url
* https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767914(v=vs.85)?redirectedfrom=MSDN
* https://github.com/electron/electron/issues/4857

**Comment by jkdev601** [comment]
Fixed in #170
