### ISSUE TITLE
Remove checkmarks from messages.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#194]
We should remove checkmarks from messages, since they don't really mean anything now.

**Comment by holmesworcester** [comment]
@jgaylor need design here too.

**Comment by jgaylor** [comment]
@holmesworcester  https://www.figma.com/file/ZE4OAg6Vi7YRsukXIQaxTq/Messages-pending-sending-grouping-checkmarks?node-id=7%3A2510 (same as the grouping designs)
