### ISSUE TITLE
Add #store channel as preloaded channel

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#197]
I'd like to demonstrate the marketplace features to all new users just to get a feel for it and dogfood the seller experience a bit.

Notes:

* add the public channel `#store` as a default channel in the left sidebar that all users see on startup
* it should display under `#zbay` and `#zbay` should still be selected by default. 
* If possible, we should preload messages for this channel as we do for `#zbay` so that all messages will be loaded right away.

**Comment by holmesworcester** [comment]
don't merge to this release. should be in next week's and qa'ed

**Comment by NorbertBodziony** [comment]
#210
