### ISSUE TITLE
Zcashd becomes unreponsive and we cannot be sure of unresponsiveness to restart/rescan

### ISSUE THREAD

**Issue by danielcybulka** [ZbayApp/zbay#198]
Win 1.0.72 dev test
Mac 1.0.74 dev test

Dislaimer: Both systems were hibernated for about week so it may be not related to update process itself.

Steps to reproduce:
1. Turn on old Zbay
2. Click sign in. After a while popup with new version appears.
3. Click update. App is being installed and after a while Zbay is up again with welcome screen. Click sign in on it.

On windows:
4. Eventually error modal appears with network error (500). Zcashd is not visible in processes.
5. After restart same thing happends.
5a. Waiting for few minutes while on error modal view eventually triggers zcashd. Then after restart app started to sync again.

On mac:
4. App stays on welcome screen with spinner inside button. Console shows refused requests with no payload. Zcashd is present in processes.
5. Restarting the app doesn't help, same zcashd process is present. Only closing it by force and restarting app helps.

Possible that it's related to #111

**Comment by holmesworcester** [comment]
Notes on this: this happens in a scenario where zcashd *may* be terminally unresponsive but *may* just be temporarily unresponsive. Sometimes zcashd is unresponsive for long stretches under normal circumstances and it's difficult or impossible to distinguish these from situations where it will not recover. Possibly there is some to distinguish but we need to test.

**Comment by holmesworcester** [comment]
@jkdev601 can you link any relevant zcashd crashing issues here? Or create issues if there is a zcashd problem that does not have a corresponding issue?

**Comment by danielcybulka** [comment]
This happened to me again after uninstalling and installing Zbay on Win. First, app was properly closed, uninstalled and installed again.

**Comment by SzymonJaworskiRF** [comment]
On version 1.0.75 macOS and 1.0.74 windows update works correctly and this error didn't occur again.
