### ISSUE TITLE
ZEC <=> USD broken validation and app crash

### ISSUE THREAD

**Issue by danielcybulka** [ZbayApp/zbay#199]
Win 1.0.72 dev test

Comma is not converted (or should be not allowed) to dot causing NaN.
![NaN](https://user-images.githubusercontent.com/67123884/86110768-43ae2a80-bac6-11ea-966a-bdd9e56855ac.PNG)

**Comment by danielcybulka** [comment]
I changed amount to proper value (0.0001) but this happened after publishing:
![Offer](https://user-images.githubusercontent.com/67123884/86111366-f2526b00-bac6-11ea-9e51-cc8d8339c9e3.PNG)

Possible that it's related to #158

**Comment by holmesworcester** [comment]
I'm going to say that this doesn't block release because it already was an issue and only affects users in this edge case. But it's close and should have been marked at such to get attention.
