### ISSUE TITLE
Selecting "Never warn me about outbound links" after clicking link has no effect

### ISSUE THREAD

**Issue by danielcybulka** [ZbayApp/zbay#201]
Win 1.0.72 dev test
Mac 1.0.74 dev test

Steps to reproduce:
( Be sure that "Never warn me about outbound links on Zbay." option in Security settings is NOT checked )
1. On chat click on link/image. Warning screen appears.
2. Select "Never warn me about outbound links on Zbay." option and click "Continue to... "

Expected: Doing so will set "Never warn me about outbound links on Zbay." global setting" to true.
Actual: Link/img is opened/loaded but settings remain unchanged. Clicking another link triggers warning again.

**Comment by NorbertBodziony** [comment]
Should be fixed by #172
