### ISSUE TITLE
Invite links do not open on linux

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#203]
@NorbertBodziony can you add proposed fix here?

**Comment by NorbertBodziony** [comment]
I checked https://www.electronjs.org/docs/api/protocol but it only supports in app based protocols so it does not solve our problem.

**Comment by holmesworcester** [comment]
@NorbertBodziony can you add everything we know about this issue to the ticket?

**Comment by holmesworcester** [comment]
ideas:
* is there another builder tool we could try that supports snaps?
* we can wrap an app image in a .deb to register links but can the app image update itself?
* can we run a separate .deb that *only* handles links (zbay-link-handler.deb)
* can we create a script that will create an entry that will allow opening URLs? can user run this script?

acceptable solution: linux user has to do a little more work to set this up and get it working, and we show an alert to them with a link on startup.

ideal solution: there's no user intervention except maybe entering a password or clicking okay or something.

doing everything the same as we do now but also making this "empty" .deb seems worth it.

**Comment by NorbertBodziony** [comment]
Linux system needs `Desktop Entry` to allow for handling a specific custom protocol. Right now we use AppImage format that does not create that entry.

**Comment by NorbertBodziony** [comment]
https://unix.stackexchange.com/questions/497146/create-a-custom-url-protocol-handler

**Comment by NorbertBodziony** [comment]
I added template file to repository and tutorial how to make it work in `README.md`
@holmesworcester Let me know if it is simple enough.

**Comment by holmesworcester** [comment]
That's good enough for now if it passes QA!

**Comment by holmesworcester** [comment]
this is complete
