### ISSUE TITLE
"Add funds" screen should disclose that funds are auto-shielded (and some general tweaks)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#209]
There are some omissions on this screen, and things are getting a bit messy.

* Change top text to:`Zbay uses the privacy-focused cryptocurrency Zcash. Cryptocurrencies let you send funds to unique addresses, like email for money: send to the correct address, and the recipient will receive it.`
* Change text above zcash t-address field to: `Deposits are moved to a private address & stored by Zbay, on your computer.`
* Change `Generate new address` link text to `New address` for transparent address.
* Change `Generate new address` link text to `New address` for private address, below.
* Change private address explanation text to: `You can't send directly to a private address from most exchanges. If sending from an exchange, use the address above, and Zbay will move all funds to a private address as soon as they arrive.`
* Change order of "Private address" and "How do I buy Zcash" so that "Private address" will be more discoverable. 

<img width="926" alt="image" src="https://user-images.githubusercontent.com/213678/86200630-38d9b100-bb2b-11ea-97d9-347914e4ad69.png">

**Comment by NorbertBodziony** [comment]
I feel like description `You can't send directly to a private address from most exchanges. Zbay will then move all funds to a private address as soon as they arrive.` does not make sense for private address. It more fit public address. 
@holmesworcester

**Comment by NorbertBodziony** [comment]
#213

**Comment by holmesworcester** [comment]
@NorbertBodziony thanks for catching that and sorry, the text in the issue was wrong. the text in the screenshot was correct! I updated the text in the issue and we can use that. I think it makes sense. `You can't send directly to a private address from most exchanges. If sending from an exchange, use the address above, and Zbay will move all funds to a private address as soon as they arrive.`

**Comment by NorbertBodziony** [comment]
Fixed in develop
