### ISSUE TITLE
Dont close window until zcashd is down.

### ISSUE THREAD

**Issue by NorbertBodziony** [ZbayApp/zbay#214]
Also show some shutting down screen

**Comment by holmesworcester** [comment]
@jgaylor can you give some instructions or a mockup of what the "Shutting down Zbay..." screen looks like?

It could just be a spinner with "Disconnecting from Zcash network..."

**Comment by holmesworcester** [comment]
@jkdev601 wasn't this issue also supposed to be addressed by killing zcashd if it was already running on startup? (granted, waiting for graceful shutdown is better)

**Comment by jgaylor** [comment]
What if we reuse this: https://www.figma.com/file/0j7Nna9zWmfOSNmRmQK1Uh/Zbay-Design?node-id=2254%3A99972

<img width="603" alt="Screenshot 2020-07-03 13 41 18" src="https://user-images.githubusercontent.com/15039182/86492181-e2d75a00-bd32-11ea-891e-18ecaf58d024.png">

**Comment by holmesworcester** [comment]
that works, yeah

**Comment by jkdev601** [comment]
> @jkdev601 wasn't this issue also supposed to be addressed by killing zcashd if it was already running on startup? (granted, waiting for graceful shutdown is better)

If this is "phantom" zcashd process we are unable to perform graceful shutdown by calling .close() only .kill() is working in that case.

**Comment by holmesworcester** [comment]
@NorbertBodziony I think this should block release if it's easy to do. How hard is it to add this?

**Comment by NorbertBodziony** [comment]
I did some quick research just to see how it will work and on linux seems like easy task.I do not know if other platform will be able to work same way.

**Comment by holmesworcester** [comment]
note:
- can't address on windows
- we can also maybe run it on start, or when the update starts

**Comment by holmesworcester** [comment]
decided we'd close
