### ISSUE TITLE
"Zbay light" can receive funds

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#224]
This ticket presupposes we make a skeleton version of Zbay with everything hard coded or mocked ("Zbay light") and try implementing features one-by-one. 

"Zbay light" should be able to receive transparent funds.

**Comment by NorbertBodziony** [comment]
It should be done already. So balance will be displayed correctly.

**Comment by NorbertBodziony** [comment]
But we still have to connect it to settings.
