### ISSUE TITLE
Write up instructions for user to run their own lightwalletd locally

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#234]
Depending on how much demand there is to maintain this feature, we may leave users on their own to run a full node, and give them instructions on how to run their own lightwalletd and get Zbay connected to it.

**Comment by NorbertBodziony** [comment]
Note: running lightwalletd basically means running zcashd with indexing. I don't think it's efficient for users to run their own nodes.

**Comment by holmesworcester** [comment]
Okay, closing.
