### ISSUE TITLE
zecwallet-light-cli should be able to see outgoing messages

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#237]
Create ticket in zecwallet-light-cli and link here

**Comment by holmesworcester** [comment]
it's present but not working. @NorbertBodziony will make a ticket

**Comment by NorbertBodziony** [comment]
https://github.com/adityapk00/zecwallet-light-cli/issues/28

**Comment by NorbertBodziony** [comment]
Fixed.

**Comment by holmesworcester** [comment]
since this is tracking an external change i'll close this for now.
