### ISSUE TITLE
Incoming transparent transaction does not appear anywhere

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#239]
Right now, incoming shielded transactions appear either in a direct message thread (if from a user) or in the "unknown" thread. However, incoming transparent transactions appear nowhere, except in a changed balance. This makes it hard to see confirmation status.  

They should appear in the "unknown" thread.

**Comment by NorbertBodziony** [comment]
Problem I see is that we move all money from transparent to shielded address and that would result in 2 entries with transfer in unknown channel.

**Comment by holmesworcester** [comment]
Let's show the transparent transaction and not the one sent to self.

**Comment by holmesworcester** [comment]
If this is relatively easy to do, I think it blocks release, since it's a bug and security related. 

If it's non trivial we can move to the next release.

**Comment by holmesworcester** [comment]
Solution: incoming t2z shielded transaction from our own transparent addresses (could be an old one) should show up in unknown. 

Here's how it ensures security and clarity of balance and funds:

1. transaction will not show up until at least one confirmation.
2. transaction will be pending until our threshold (24?) 
3. transaction will disappear if there is a reorg before then and zcashd corrects.
