### ISSUE TITLE
Channel loading indicator needs bottom margin

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#240]
Loading indicator on messages view needs some margin; right now it's flush with bottom of the screen, which looks broken. 90px margin from bottom of the screen would work

<img width="586" alt="image" src="https://user-images.githubusercontent.com/213678/86485320-72c2d700-bd26-11ea-8134-839177226d5b.png">

**Comment by jkdev601** [comment]
Fix in #254
