### ISSUE TITLE
Team should receive automated alerts when faucet fails 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#242]
When the faucet breaks it negatively affects user experience. We should get an automated SMS alert when it goes down, using pingdom or similar.

**Comment by NorbertBodziony** [comment]
We can send email or sms with some raw data, or we can go with more advanced version where we parse a message, and we can send message to slack with something like "Faucet is currently down". Right now i will get email notification when Faucet dies.

**Comment by holmesworcester** [comment]
Can you set your email notifications so that they trigger a unique
notification on your phone in this case? And can you add my email so that I
can do the same?

**Comment by holmesworcester** [comment]
add hw to these notifications

**Comment by holmesworcester** [comment]
then close
