### ISSUE TITLE
Space after t-address in "send funds" makes memo field available, causes crash.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#243]
Steps to reproduce:

1. Click send funds
2. Enter a valid t-address. Note how no memo field appears
3. Type a space after the t-address

Expected: no memo text field appears because I'm still sending to a t-address

Actual: memo text field appears. Enter text in the field and hit send, and app shows javascript error and must be restarted.

**Comment by jkdev601** [comment]
Fix in #251
