### ISSUE TITLE
Zbay prompts first time user to create username, even when balance is zero

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#244]
If the faucet fails (which will happen sometimes) or if the send to the user does not go through properly, the user will have no funds when they finish the sync process.

Currently, zbay will prompt them to register a username even if they do not have funds.  

Zbay should not prompt them to register a username in this way if they have no funds. If funds are zero, they should land in the main screen and be prompted to add funds when they take actions that require it.

**Comment by jkdev601** [comment]
Fix in #252

**Comment by SzymonJaworskiRF** [comment]
Checked and approved by @jkdev601
