### ISSUE TITLE
Offers in #store channel are not visible to a fully-synced user

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#247]
See thread in #store channel for more information. A user is fully synced but cannot see offers I've posted to the store, even though they can see all my messages more recent messages to the same channel.

I believe I hid *one* offer message using a moderation message. So there could be a problem with parsing of moderation messages.

**Comment by holmesworcester** [comment]
@NorbertBodziony can you reproduce this? i cannot.

**Comment by NorbertBodziony** [comment]
I think store as default channel feature is not in release so right now user that joins that channel will only see last 2000 blocks.

**Comment by holmesworcester** [comment]
Okay, closing this and making a ticket for the general issue, which is still important but lower priority.
