### ISSUE TITLE
When creating new channel, the validation message should display better info about hyphen usage

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#256]
Information displayed in validation message should say something like: "You cannot start or end channel name with hyphen".

![Zrzut ekranu 2020-07-7 o 01 39 32](https://user-images.githubusercontent.com/67907892/86750796-10522b00-bff3-11ea-9205-a35cd1d427a8.png)

**Comment by holmesworcester** [comment]
Like #258 we should just enforce this

**Comment by holmesworcester** [comment]
@SzymonJaworskiRF this can be marked as a bug because it's not giving the user the correct information.

**Comment by holmesworcester** [comment]
i'm going to close this as covered by the solution to #258
