### ISSUE TITLE
Validation message shows that channel will be created even tho validation has failed and channel name contains too many hyphens.

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#257]
![Zrzut ekranu 2020-07-7 o 01 57 33](https://user-images.githubusercontent.com/67907892/86753860-47294080-bff5-11ea-8953-18a212990e02.png)

**Comment by holmesworcester** [comment]
Related to #258 I think we should enforce this, that is, control what the user is able to type into this field.

**Comment by holmesworcester** [comment]
We could include a line of text above the form field or below the button that says: 

"Channel names must be less than 20 characters long, lowercase letters and numbers only. You can use hyphens for spacing if you like."

**Comment by holmesworcester** [comment]
i'm going to close this as covered by the solution to #258
