### ISSUE TITLE
Improve channel creation validation on first window open.

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#258]
On opening "channel creation modal" and typing your channel name, validation after exceeding the maximum length of a channel name, typing invalid characters or  including too many hyphens happens after leaving the input. It might be good to display the validation message to the user immediately after he breaks channel creation rules. 

![Zrzut ekranu 2020-07-7 o 02 04 39](https://user-images.githubusercontent.com/67907892/86755772-bd7a7280-bff6-11ea-8e00-73e3cc23e897.png)

**Comment by holmesworcester** [comment]
I think the best way to do this is to "enforce" the rules as the user types.

**Comment by holmesworcester** [comment]
marking this a bug because the user can break things without getting a clear message

**Comment by holmesworcester** [comment]
We should also include some text that says: "Channel names must be less than 20 characters long, lowercase letters and numbers only. Hyphens can be used for spacing." Below the title.

**Comment by NorbertBodziony** [comment]
#275

**Comment by SzymonJaworskiRF** [comment]
If I try to put more than 1 hyphen in the middle of the channel name, the validation error appears. Also when I try to start or end channel name with a hyphen I get a validation error message, but it does not say that the channel name can't start/end with hyphen. I think it should be a message with different text.

![Zrzut ekranu 2020-07-14 o 02 39 10](https://user-images.githubusercontent.com/67907892/87410689-7c94d780-c57b-11ea-8c93-47667e7cd3b8.png)

**Comment by holmesworcester** [comment]
Yeah I think it should show us what the name of the channel is, as if we
used spaces.

Holmes

**Comment by NorbertBodziony** [comment]
Fixed.
