### ISSUE TITLE
Scrollbar is displayed behind messages which makes it barely visible.

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#260]
This bug occurs on any channel that allows scrolling but only on macOS system.

link: [link to issue #129](https://github.com/ZbayApp/zbay/issues/129)

![Zrzut ekranu 2020-07-7 o 05 10 06](https://user-images.githubusercontent.com/67907892/86779515-85802900-c010-11ea-8128-de58b34831bb.png)

**Comment by holmesworcester** [comment]
I can't reproduce this but perhaps it's just a bug in the new RC?
