### ISSUE TITLE
Cannot send message with emojis.

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#261]
After trying to send a message with emoji, the app sends the message but without emoji and message input is not being cleared.

Steps to reproduce:
* pick a person you want to send a message to
* type a message with emoji
* send a message

![Zrzut ekranu 2020-07-7 o 05 33 27](https://user-images.githubusercontent.com/67907892/86782074-836b9980-c013-11ea-9a51-dc2f70a37895.png)

**Comment by holmesworcester** [comment]
i'm able to send emojis on single lines
