### ISSUE TITLE
Amount of money payed rounds to 0.00$.

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#263]
![Zrzut ekranu 2020-07-7 o 06 56 12](https://user-images.githubusercontent.com/67907892/86792100-00504080-c01f-11ea-9acd-e4bd6a4d4ef5.png)

**Comment by holmesworcester** [comment]
Note: fix should round USD to 0.01 in this case and ZEC amount should be the same.

**Comment by holmesworcester** [comment]
prioritizing because it affects accuracy of funds

**Comment by NorbertBodziony** [comment]
#276

**Comment by SzymonJaworskiRF** [comment]
Now I'm seeing bugs with rounding values up incorrectly and I suspect that they are related. It happens for old transactions as well as for the new ones.

![Zrzut ekranu 2020-07-15 o 04 22 32](https://user-images.githubusercontent.com/67907892/87539585-ffd52c80-c652-11ea-8c1d-63cac2a31a22.png)

**Comment by holmesworcester** [comment]
Money bugs block release..

**Comment by NorbertBodziony** [comment]
Fixed. Rounding will be normal but message details will show full amount in ZEC.
