### ISSUE TITLE
Shipping form displays validation errors and breaks the app.

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#266]
Shipping form displays validation errors after shipping info update even tho field has a correct value. Additionally when you switch to another setting,  switch back to shipping form and click "ctrl+backspace" the app breaks.

Steps to reproduce:

* Go to "shipping" setting
* Go to update city field
* Update city value
* Click "save" button
* Switch to "account" setting
* Switch back to "shipping" setting
* Click on Country field
* Click away from country field
* Click on Country field again
* Press "ctrl+backspace" on windows or "cmd+backspace" on macOS

![Zrzut ekranu 2020-07-7 o 07 43 14](https://user-images.githubusercontent.com/67907892/86798449-a56e1780-c025-11ea-9efe-9debf41cad37.png)

**Comment by holmesworcester** [comment]
I was able to reproduce the "white screen" crash just by editing city name after saving it.

**Comment by NorbertBodziony** [comment]
#292
