### ISSUE TITLE
Adding public channel shows incorrect messages to user

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#282]
steps to reproduce:

1. click "find channel"
2. choose #aaaa 

expected: should show green success alert, add #aaaa to sidebar, make that the selected channel, show a view of the channel with "loading messages" until messages are loaded.

actual: shows spinner in modal while messages are loading. when i close modal, shows a message that makes it sound like i created the channel:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/213678/87113159-9cef2a00-c23b-11ea-9890-540d61c7e9e8.png">

**Comment by NorbertBodziony** [comment]
#293
