### ISSUE TITLE
"White screen" crash when user edits zipcode 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#283]
Steps to reproduce white screen crash:

1. Go to shipping screen
2. Edit zipcode
3. Save
4. Go to "add funds"
5. Go back to settings.
6. Edit zipcode

Bonus: fix all whitescreen issues once and for all! Catch them using the standard react mechanism for this, show a red alert error or a modal with as much info as possible and option to send to us, and return user to a working homescreen!

**Comment by NorbertBodziony** [comment]
Duplicate closing. #266
