### ISSUE TITLE
Sending a message to another user shows “loading messages” instead of just showing the DM

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#288]
Steps to reproduce:

1. send messages to another user who you have never messaged before.

expected: you see an empty thread with them immediately and can send the first message.

actual: you see a "loading messages" spinner even though there could not possibly be any messages!

**Comment by NorbertBodziony** [comment]
So this behavior occurs only if you try to send a message just after application start. Reason for that there is global flag that is loading messages and that user may already send you message we just don't know about it. If you try to send message to user after initial load is done it will behave as expected.

**Comment by holmesworcester** [comment]
Can we disable for first time user?

**Comment by holmesworcester** [comment]
@NorbertBodziony ^

**Comment by jkdev601** [comment]
Fix in #311
