### ISSUE TITLE
Seller does not see address

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#299]
Steps to reproduce:

1. go to store.
2. buy "stickers"

expected: both user and seller see shipping address alongside funds sent.

actual: i see shipping address in funds sent, but seller doesn't. 

I can provide screenshots privately.

**Comment by NorbertBodziony** [comment]
I have fixed it, but we will need add validation to size of shipping information since it may cause signature check failure.

**Comment by NorbertBodziony** [comment]
New ticket for adding validation of size #306
