### ISSUE TITLE
Private Zcash address displaying on "Add funds" screen should never be user's published address

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#300]
Users should never accidentally reveal their identity by giving out their private address. When Zbay shows you a private address it should not be the same as the address you published when you create an account

**Comment by holmesworcester** [comment]
@NorbertBodziony is this already how things work? I just wanted to create a ticket to track it.

**Comment by NorbertBodziony** [comment]
No but it is simple fix only downside is that we have to keep track of another address and that slows down zcashd. By the way Litewallet-cli makes it super simple, so we don't have to worry about moving assets between addresses.

**Comment by holmesworcester** [comment]
Okay great. Let's address this soon then.
