### ISSUE TITLE
"Value when sent" field shows incorrect value

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#304]
Description: After opening transaction details, the "value when sent" field displays incorrect amount of money. It happens on every transaction I open.

Steps to reproduce:
* Open a transaction detail screen.
 
![Zrzut ekranu 2020-07-14 o 02 22 30](https://user-images.githubusercontent.com/67907892/87408967-1e66f500-c579-11ea-99c9-6f412c1af394.png)

**Comment by jkdev601** [comment]
Fix in #329
