### ISSUE TITLE
User should not have to scroll down to see new messages

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#308]
When a user opens Zbay, or switches channels, message threads should be scrolled to the most recent message, so that you can always see that you received new messages.

This is a quick fix and at some point we will want to implement something like this: https://www.figma.com/file/0j7Nna9zWmfOSNmRmQK1Uh/Zbay-Design?node-id=1057%3A28805

**Comment by holmesworcester** [comment]
Worse, it makes you scroll down again when you click back to the thread, if you sent a message.

**Comment by NorbertBodziony** [comment]
When you switch channel you always should be scrolled to bottom if not please provide steps to reproduce.

**Comment by NorbertBodziony** [comment]
#331

**Comment by NorbertBodziony** [comment]
This fix changes that when you send message scroll will move to bottom.
