### ISSUE TITLE
Incorrect amount of money displayed

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#328]
Description: I'm specifying amount of money I want to send in ZEC (before I was doing so in USD) and on the screen that confirms my transaction (named "transaction details") I see incorrect amount of money sent.
Platform: win & mac

Steps to reproduce:
* click send money
* type 0.001 in ZEC field
* click send

Expected behavior: When I send 0.06 ZEC I should see 0.0600000 ZEC in "total" field instead of "0.0600025"

![Zrzut ekranu 2020-07-21 o 07 01 19](https://user-images.githubusercontent.com/67907892/88064530-424dac00-cb20-11ea-943a-99b95c88c25d.png)

**Comment by jkdev601** [comment]
Fix in #332
