### ISSUE TITLE
ZbayLite cannot start and sync on Mac 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#335]
The behavior is a bit hard to explain, but @NorbertBodziony saw it. We should see if you can reproduce it on a Mac.

**Comment by NorbertBodziony** [comment]
On our mac it works smooth it seems like it caused by neon builder and caching. You should remove entire ZbayLite repository wallet and zbay-lite folder. Then download fresh Zbaylite repository from github and run initial steps as before.

**Comment by holmesworcester** [comment]
okay awesome.

**Comment by NorbertBodziony** [comment]
@holmesworcester can you let me know if you were able to run app?

**Comment by holmesworcester** [comment]
yep, working fine now
