### ISSUE TITLE
Create a new private channel - invalid error message

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#339]
Description: upon trying to create a channel invalid error message appears after exceeding maximum number of characters. There should be no info that channel will be created.

Platfodm: mac os
Version: 1.0.73-dev-2

Steps to reproduce:
* Edit channel name aggressively.

![Zrzut ekranu 2020-07-28 o 01 43 00](https://user-images.githubusercontent.com/67907892/88641371-f5179000-d073-11ea-97b1-ef341bdea2c4.png)

**Comment by holmesworcester** [comment]
There have been a bunch of bugs in this. Is there some generic solution or library for enforcing rules on text input that we could use here?

**Comment by holmesworcester** [comment]
not blocking but let's fix this coming week.

**Comment by NorbertBodziony** [comment]
Actually it's order of errors triggered we do not show all errors in validation because it seems extensive. Also, error message is valid channel name is too long once you fix it other errors will popup.

**Comment by kingalg** [comment]
Checked - I confirm that this is fixed.
