### ISSUE TITLE
"Buy" for offers without required address is not working

### ISSUE THREAD

**Issue by SzymonJaworskiRF** [ZbayApp/zbay#344]
Description: when the user posts an offer without the required address and someone buys it the seller doesn't receive the information that his offer has been bought. It happens on both mac os and windows. Adding address by the buyer to an offer that doesn't require it also generates a bug. 

Platform: mac os, windows

Steps to reproduce:
* Create an offer without required address
* Buy this offer from another account
* Check that the seller doesn't receive information that his offer is bought and the funds - this is not correct behavior

Additional info: messages sent by the buyer to the seller through an offer are working as expected. On the screen added to this bug, you can see an offer that has been bought over an hour ago and it's still not processed. The message went through without problem.

![Adnotacja 2020-07-28 153045](https://user-images.githubusercontent.com/67907892/88672075-53ca2180-d0e7-11ea-958b-422ce13dcba9.png)

**Comment by holmesworcester** [comment]
Did this bug just appear in this iteration? Or did we miss it in the last QA? @SzymonJaworskiRF

**Comment by SzymonJaworskiRF** [comment]
I don't think I've experienced it in the last QA so it must be a new bug.

**Comment by jkdev601** [comment]
Fix in #330
