### ISSUE TITLE
Allow ZbayLite user to "remove" channel (channel actions menu)

### ISSUE THREAD

**Issue by jkdev601** [ZbayApp/zbay#359]

**Comment by kingalg** [comment]
Channels (both private and public) can be removed from the channel list. The user receives a pop-up with a question if he is sure that he wants to remove this channel (options yes and no). After clicking Yes the channel is removed and green success pop-up is displayed. Choosing No option close No/Yes pop-up and move the user to the channel window. Everything is working as expected.
