### ISSUE TITLE
Sending message in ZbayLite fails

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#365]
Steps to reproduce:

1. install zbaylite
2. register username
3. send message

message appears after restart, not sure if it goes to chain, but error message always displays and requires restart

<img width="807" alt="image" src="https://user-images.githubusercontent.com/213678/89203692-fb7d9e80-d582-11ea-9c6e-6ef465152e26.png">

**Comment by holmesworcester** [comment]
update: if i restart too quickly it seems that the message does not go through.

**Comment by jkdev601** [comment]
Fixed

**Comment by kingalg** [comment]
Checked - fixed.
