### ISSUE TITLE
ZbayLite appears to run out of UTXOs even when 100% synced

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#371]
<img width="225" alt="image" src="https://user-images.githubusercontent.com/213678/89480917-91bcea80-d764-11ea-9f9d-13813275cfab.png">

Maybe the free UTXO count simply isn't correct?

**Comment by NorbertBodziony** [comment]
We do not have utxo spliter right now and each utxo require 5 blocks of cooldown so you will run out of utxo quickly.

**Comment by holmesworcester** [comment]
i’m not sure if the 5 blocks of cooldown works to reset it. i’m still at zero hours later.

**Comment by holmesworcester** [comment]
what’s going to be our solution for this? 

one idea: keep the randomization of number of notes, but cap it at 2/3 of notes.

H

**Comment by NorbertBodziony** [comment]
Please pull new version of zbaylite old one got broken balance calculation. So you may be out of money.

**Comment by NorbertBodziony** [comment]
Utxos will work just like on full version, so I don't think we have to do anything special.
