### ISSUE TITLE
ZbayLite should include Tor and connect via Tor by default

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#399]
* Zbay's build process should include the latest Tor binary
* We should have a process to ensure that a new version of Zbay happens whenever there is a new release of Tor, so that the user always has the latest version of Tor. 

Note that this should be a naive implementation: connect over Tor, never directly. We will not make any privacy claims about the impact of this integration because transactions could still be linkable.

**Comment by NorbertBodziony** [comment]
Tor binary will be included with new release but only for p2p communication zcash cli will not use tor.

**Comment by holmesworcester** [comment]
Full support requires modification of the networking library that zecwallet-light-cli uses or switching to a different networking library. 

Or we can use netcat on Mac and Linux to "wrap" zecwallet-light-cli and send all traffic to Tor. (There may be issues with DNS)

Can we use http tunnel?

**Comment by holmesworcester** [comment]
Question: does [httptunnel](https://2019.www.torproject.org/docs/tor-manual.html.en#HTTPTunnelPort) allow us to provide a .onion URL?

**Comment by NorbertBodziony** [comment]
I have looked into cli code and web library that it is using does not support tor. Wrapping app in some other program may be overkill and it will not solve issue for windows. I think best bet is to modify cli code or just add proxy server.

**Comment by holmesworcester** [comment]
We're closing this for now, until this is supported by zecwallet-light-cli.
