### ISSUE TITLE
Channel name not visible in ZbayLite

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#404]
Steps to repro:

Open main window, join #zbay channel.

Expected: "#zbay" channel name displays in top bar above participants count.
Actual: name is missing. 

Note: This bug only happened for me on startup. When I changed channels, the name appeared. I can however reproduce this on every startup.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/213678/90565968-b27a3c80-e175-11ea-9404-40d95628da17.png">

**Comment by kingalg** [comment]
After startup name of the channel "zbay" is present. Bug fixed.
