### ISSUE TITLE
Update add funds screen to display QR code for shielded address 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#412]
(let's discuss)

**Comment by jgaylor** [comment]
Latest design: https://www.figma.com/file/0j7Nna9zWmfOSNmRmQK1Uh/Zbay-Design?node-id=2590%3A422687

**Comment by holmesworcester** [comment]
@jgaylor that link is broken and I tried to find the design but can't.

**Comment by jgaylor** [comment]
@holmesworcester here you go: https://www.figma.com/file/EQ1Q2Em2MuJh7XsOkd0IbE/Add-funds?node-id=12%3A891
