### ISSUE TITLE
Alert that I mentioned someone who is not a participant appeared, when they *were* a participant

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#414]
Steps to reproduce;

1. fresh install of zbaylite
2. @mention a user who has written a message in the chat

expected: no warning

actual: warning appears prompting me to invite them

**Comment by kingalg** [comment]
It's working now. When mentioned user is a participant there is no warning. It's also working correctly for the user that is not a participant - in this case appropriate information is displayed.
