### ISSUE TITLE
User should be able to import paper backup and restore from it 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#422]
Relates to: https://github.com/ZbayApp/zbay/issues/189

A new user should be able to restore their account and their funds from a paper backup.

**Comment by holmesworcester** [comment]
Possible places for this:

- intro slides
- or just on the opening screen. 

opening screen is best

**Comment by jgaylor** [comment]
design: https://www.figma.com/file/NGKiJUepb3NWKtUh2GShAY/Recovery-Key?node-id=7%3A2518

**Comment by holmesworcester** [comment]
Note that this would only display when people are creating an account after a fresh install. Not on the "Welcome back" screen.

**Comment by holmesworcester** [comment]
@jgaylor can you update the link to the design here?

**Comment by jgaylor** [comment]
@holmesworcester I updated the link.
