### ISSUE TITLE
Wrong message after the user try to remove "unknown" channel

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#441]
Description: tab "unknown" in Direct Messages section should be unremovable from left side menu (and it is). However option "Remove" is available for this channel and choosing it generates success message "Successfully removed channel".

System: Zbay Lite, Windows and MacOS

Solution - either option "remove" should not be available for "unknown" or choosing this option should generate message informing that removing this channel is not possible.

**Comment by holmesworcester** [comment]
I think removing should be possible. It should just re-appear when you receive a new tx there.

**Comment by holmesworcester** [comment]
@NorbertBodziony can you confirm that it will reappear if removed, when there is a new transaction? (just as direct message would?)

**Comment by holmesworcester** [comment]
this is a little bad since we're using it as the place where users see what funds they've received. but...
