### ISSUE TITLE
Channels for direct messages are not created when the message arrives

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#442]
Description: Channels for direct messages are not created when the message arrive. They are also not created when the user is searched through "create a new message". In the second case the channel opens but there it's not on the side left panel (see attached screenshot) so it can not be access easily. Messages are coming through the chain as there are pop-ups with a content of a message. 

Steps to recreate: send a direct message to a user that is not listed on left side panel. 

![Adnotacja 2020-09-02 164027](https://user-images.githubusercontent.com/68909168/92000384-bee9c200-ed3d-11ea-96dc-0a2de496bc75.png)

**Comment by holmesworcester** [comment]
yep, this is a blocker

**Comment by holmesworcester** [comment]
was this fixed? heisenbug?

**Comment by holmesworcester** [comment]
@kingalg can you reopen this if it happens again?
