### ISSUE TITLE
Temporarily hide transparent address

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#445]
Because we cannot auto-shield transparent deposits, we should hide the transparent address for now. 

Note the additional text about why we are hiding transparent addresses. "This issue" should link to our issue. 

Here's a mockup of what it should look like:  

<img width="676" alt="image" src="https://user-images.githubusercontent.com/213678/92120419-07998d80-edc7-11ea-98f3-4b3247aa18c5.png">

(Bonus: add a QR code to private address so people don't have to copy/paste... I think there is another ticket for this somewhere)

**Comment by kingalg** [comment]
Transparent address is hidden as described and QR code is added. This temporary solution has been implemented correctly.
