### ISSUE TITLE
Error message after upgrade

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#456]
Not sure why I'm getting this. I may have been getting it before the upgrade too. Could be specific to me.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/213678/92275381-05195f80-eebd-11ea-9868-11a7129d1fd9.png">

**Comment by kingalg** [comment]
As Norbert states that this is done and I didn't encounter this bug during my checks this week I'm closing this.
