### ISSUE TITLE
Zbay doesn't let computer sleep?

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#474]
I'm not 100% sure if this is the case, but it seems from casual use that Zbay will not let my computer sleep. 

I forget what Zbay heavy's behavior was, but can Zbay lite behave differently?

**Comment by NorbertBodziony** [comment]
We were only blocking sleep during rescan of full node. It's no longer valid in zbay lite.

**Comment by holmesworcester** [comment]
seems invalid
