### ISSUE TITLE
Show username (not anonxxxxx) in top left status area as soon as user chooses it, even if it isn't registered yet. 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#475]
It's confusing that you choose a username but are still anonymous.

1. We should show the user's chosen username in the top left from the first moment they arrive in the app.
2. When the user is waiting for funds, we should have a closeable but *not-disappearing* snackbar notification that says "Waiting for funds to register username—this can take a few minutes."
3. When username registration is sent it should change to: "Registering username—this can take a few minutes."
4. When our user registration message appears on the channel and has our confirmation threshold for payments (10? 24?) we should say "Username registered."
5. If it is not mined after 5 (?) blocks we should say "Username registration failed. Retrying..." and retry automatically. 
6. User can send DMs as soon as funds arrive, but recipient will not see them until the username registration is complete and the recipient can verify their identity. When it's complete they will appear as normal messages. 

@NorbertBodziony thoughts on this approach?

(Also, please take the discussion in the thread below as context but feel free to ignore it. There are a bunch of ideas in here about other possible approaches.)

**Comment by holmesworcester** [comment]
Alternately, we could make the user wait for their registration to go through. Thoughts on this @NorbertBodziony @jkdev601

**Comment by NorbertBodziony** [comment]
Honestly it's much easier to just immediately mock username. Checking if username is public will have to happen on every loop, and we will need to compare it with existing ones. We are only waiting for confirmation of transaction. We already handle cases if transaction fails .

**Comment by NorbertBodziony** [comment]
I want to mention that we can allow user to send messages immediately because ordering should stay right if miners do not filter username message.

**Comment by holmesworcester** [comment]
You mean, we could let users send messages before funds are received, mock these, and send when funds received?

**Comment by holmesworcester** [comment]
I think we should mock the username and show "pending..." until transaction is confirmed.

**Comment by holmesworcester** [comment]
@jgaylor review how it is now and let's discuss?

**Comment by holmesworcester** [comment]
We could show a spinner next to the username with a tooltip.

**Comment by holmesworcester** [comment]
Actually, thinking about this more I think we need to create an API where the user can send us their username choice via Tor, tell them if it's taken, and register the address on chain ourselves, asserting that it's the first registration of that username. This will let us register a username right away.

**Comment by holmesworcester** [comment]
@NorbertBodziony 

So are these the options?

1. Send username registration immediately with 0 value, 0 fee. 
2. Provide signed username registration message to us, then we send to network. 
3. Wait to send registration message until we receive funds from the faucet, but show username registered right away. 

Option 1 risk: it doesn't go through. 
Option 2 risk: it trusts us in some way. We could register our own address, and man in the middle them (I think?)
Option 3 risk: username registration fails or takes longer than we think. 

Let's discuss this. Also let's discuss this: https://github.com/ZbayApp/zbay/issues/517

**Comment by NorbertBodziony** [comment]
My option is that we just stick with the flow, but we just "Mock" internally username. The order of messages in 9/10 cases will be the same so even if the user sends dm to somebody we can assume it will not arrive before the username.

**Comment by holmesworcester** [comment]
Let’s show some non-disappearing blue or yellow snackbar notification that says “registering username” and it only disappears once we see the transaction. Does that work?

**Comment by kingalg** [comment]
Username is visible directly after registration and the user can see a blue non-disappearing snackbar with information (user can choose to close it but it will not be close without user action).
