### ISSUE TITLE
Mac dock icon "badge" for new messages doesn't disappear, increases indefinitely. 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#480]
I can't reproduce this, but a user on Zbay 2.0.1-zbay-lite is reporting an issue with notifications and the macOS "dock icon badge" .

The number in the red circle keeps increasing even though messages have been read.

**Comment by rex4539** [comment]
@NorbertBodziony should be aware of this. I have reported it on Slack on August 14th.

**Comment by holmesworcester** [comment]
Excellent, thank you!

**Comment by kingalg** [comment]
It is working nicely on my Mac on the newest version (updated today).

**Comment by rex4539** [comment]
Is there a release with the fix available? Latest one still has the bug.
