### ISSUE TITLE
User is able to register same username multiple times 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#493]
The user pkr registered their username yesterday or over the weekend.

The same user just registered it today. This shouldn't be possible. 

<img width="590" alt="image" src="https://user-images.githubusercontent.com/213678/93923363-4abd9100-fce1-11ea-92be-0a23f6dbcab7.png">

**Comment by holmesworcester** [comment]
@NorbertBodziony @jkdev601 what's likely happening here?

**Comment by pruhstal** [comment]
I believe it's happening somewhere around here: https://github.com/ZbayApp/ZbayLite/blob/a6535a8172f9ab654cb77481e1a225a22179f03d/src/renderer/store/handlers/users.js#L182 given that I'm never seeing that snackbar msg: https://github.com/ZbayApp/ZbayLite/blob/a6535a8172f9ab654cb77481e1a225a22179f03d/src/renderer/store/handlers/users.js#L186-L192

**Comment by NorbertBodziony** [comment]
Related https://github.com/ZbayApp/zbay/issues/492

**Comment by holmesworcester** [comment]
@pruhstal I'll reach out on signal about getting account data from you that can help us fix this.

**Comment by holmesworcester** [comment]
closing as duplicate.
