### ISSUE TITLE
Shielding funds from transparent address not working

### ISSUE THREAD

**Issue by jkdev601** [ZbayApp/zbay#495]
Transparent address presented in add funds tab is not included into transparent address array which belongs to wallet. 
![Zrzut ekranu 2020-09-25 o 10 26 09](https://user-images.githubusercontent.com/37960169/94245467-960eb400-ff1a-11ea-97d5-74d5e4d0c74b.png)

**Comment by jkdev601** [comment]
I've checked this field on newly created account and for migrated account without above issue. We decided with @NorbertBodziony that it was caused by installing new version on computer with some leftovers from previous installation.

**Comment by holmesworcester** [comment]
This is bad!

@jkdev601 Do we have any idea how many users this affected? We should push this update soon.
