### ISSUE TITLE
User should be able to see when another user is online

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#499]
We're adding functionality for messaging directly over Tor. This will let us see in some cases when another user is online. 

If a user is online, we should show some indication of this. Design below. We should implement the sidebar and top bar changes. 

We won't implement any indication of online status in the user profile popup, as in the design. We're just showing online status for people in the sidebar. 

The placeholder text in message field should change to. "Message @user as @holmes directly with no fee."

**Comment by jgaylor** [comment]
@holmesworcester here's a rough first pass on this: https://www.figma.com/file/0j7Nna9zWmfOSNmRmQK1Uh/Zbay-Design?node-id=2556%3A167202

Added some notes/considerations as well. Let me know what you think.

**Comment by jgaylor** [comment]
All set on this. Assigning to you.

**Comment by holmesworcester** [comment]
@NorbertBodziony we could simplify this ticket by just showing the online status in a DM thread when you're already connected. That way we don't have to worry about connecting to everyone on startup. Or is that the same?

**Comment by NorbertBodziony** [comment]
Check itself takes about 8 sec so there may be delay. I think we can fit connection to all users on start of app and check how it will perform.

**Comment by holmesworcester** [comment]
Okay great

**Comment by holmesworcester** [comment]
@NorbertBodziony is this done and in the release? i saw kinga reported a bug from it.

**Comment by holmesworcester** [comment]
The user modal design change is optional, so this is done. The sidebar was the most important piece.
