### ISSUE TITLE
Registered user appears as anonymous.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#503]
Steps to reproduce:

1. fresh install
2. restart.

expected: these messages are sent from holmes and should appear as such.

actual: they appear as being from an anonymous user.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/213678/94814321-2d668200-03c7-11eb-84f9-891774b5c3c6.png">

**Comment by jkdev601** [comment]
Sometimes store doesn't contains all usernames. It's fixed after restart of the app.

**Comment by holmesworcester** [comment]
@jkdev601 can you add details of your observations to the ticket?

**Comment by NorbertBodziony** [comment]
There is hotfix that skips wrong state that may be causing skipping entire loop for usernames.

**Comment by holmesworcester** [comment]
Progress on this?

**Comment by NorbertBodziony** [comment]
I may add delay to start of application. @holmesworcester

**Comment by holmesworcester** [comment]
I think this is okay. How much of a delay? 

Tell me more about the need for it?

**Comment by NorbertBodziony** [comment]
So we need another round to load latest messages but this is connected with syncing on start. If we skip sync on start i will not matter.

**Comment by holmesworcester** [comment]
We decided to not change the startup sequence, so let’s just do the minimum to fix this issue now.
