### ISSUE TITLE
User can't register a username with existing username as first n letters

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#504]
Steps to reproduce:

1. Try to register a username like "holmes23424"

expected: you can
actual: it prevents you from typing after you match with an existing username, and shows an error.

(I'm seeing this in the WSclient branch, not master)

**Comment by holmesworcester** [comment]
Wait. This only happens when *re-registering* a username, which shouldn't really be possible anyway. This bug might be invalid.

**Comment by NorbertBodziony** [comment]
i think its invalid.
