### ISSUE TITLE
Show indicator that the user you're talking to is typing 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#505]
Now that we have real-time off-chain messaging working, we should show some indication that a user is typing when you are connected via tor. 

Design is here. Ignore link below! https://www.figma.com/file/FpEcAJe8HCFOFJRVwujPzH/Typing-status?node-id=7%3A2510

**Comment by jgaylor** [comment]
@holmesworcester First pass on this: https://www.figma.com/file/0j7Nna9zWmfOSNmRmQK1Uh/Zbay-Design?node-id=2560%3A301

**Comment by holmesworcester** [comment]
this looks good as is.

**Comment by jgaylor** [comment]
@holmesworcester  Ok, i added your notes and cleaned it up. Assigning to you

**Comment by holmesworcester** [comment]
@jgaylor can you update the link here?

**Comment by holmesworcester** [comment]
nm, got it.
