### ISSUE TITLE
Can't send a message from zbay on Windows - "please check node connection" 

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#507]
Sending messages from Zbay on Windows stopped working. I've tried to restart program and restart computer as well but it didn't changed anything. Popup that is displayed said: couldn't send a message, please check node connection.

Update: after half an hour it started working again (no changes done on user side).

**Comment by holmesworcester** [comment]
@kingalg what error message displayed?

**Comment by holmesworcester** [comment]
This might be because we had overlapping versions. @kingalg please close this if you can't reproduce in the next few weeks working with clean versions.

**Comment by holmesworcester** [comment]
Actually, closing now and let's reopen if we see it again. @kingalg does that work for you?
