### ISSUE TITLE
Sending the funds to minimalized zbay on Mac results with crashing senders app

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#512]
Descritpion: If the user send the funds to account on zbay installed on Mac that is minimalized senders app will crash. Any future try of sending new funds to this account will result with an error. Sender may still send and receive funds from another users.

Platform: MacOs 

How to recreate:
1. Minimalize zbay on MacOs.
2. Try tu send there funds from another account.
3. An error will occur on senders app.

![Capture](https://user-images.githubusercontent.com/68909168/95328300-aa04cf00-08a5-11eb-98d7-4f7d2ad1edd4.PNG)

**Comment by NorbertBodziony** [comment]
I think this is connected with Web sockets feature. Should be resolved.

**Comment by kingalg** [comment]
Fixed.
