### ISSUE TITLE
Remove donate option because it's no longer possible

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#514]
To reproduce: on add funds screen, click "Donate 1% of my deposit..."

Expected: checkbox selects

Actual: green alert displays, but checkbox doesn't select. 

Also, this should be selected by default if it isn't yet.

**Comment by NorbertBodziony** [comment]
Note: We are unable to make it work right now during shielding balance. We can create another transfer once funds are shielded.

**Comment by NorbertBodziony** [comment]
We should remove this since it does nothing right now.
