### ISSUE TITLE
Channels are not created for direct messages on Windows

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#521]
Description: Channels are not created for direct messages on Windows. The user can send a message to another user via direct message but o new channel is created in the left panel. When the user receive a new message there is also no new channel however if he opens a channel by "create new message" button he can see the message.

Platform: problems occurred only on WIndows.

Steps to recreate:
- open zbay on WIndows
- send direct message to a different user
- check if a new channel has been created for this conversation

![image](https://user-images.githubusercontent.com/68909168/96585284-3941b780-1294-11eb-9ca6-4a827b02158a.png)

**Comment by holmesworcester** [comment]
It's also weird that the user has a DM thread with themselves.

**Comment by kingalg** [comment]
Creating channel for private messages is working.
