### ISSUE TITLE
Should display bolded channel name after receiving a new message - not working

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#523]
Description: after the user receive new message the channels name is not bolded. 

Platform: WIndows and Mac

Steps to recreate:
- send a new message in a channel where another user is a participant (make sure that second user is in a different channel once awaiting a message)

**Comment by holmesworcester** [comment]
@jgaylor do we have a design for a slack-like unread count on DM threads and channels? Like a red badge with the unread number, or something to make this more visible than just the bolding?

**Comment by jgaylor** [comment]
@holmesworcester we did some work on this here: https://www.figma.com/file/UAK1sz35A3glgS2T2tWUxJ/Sidebar-Unread-messages-mentions-badges?node-id=7%3A2518
