### ISSUE TITLE
Can't buy an offer with shipping information required

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#524]
Description: user can not buy an offer with shipping informations required. It looks fine at the beginning - offer is posted, another user can send a message about this offer that creates a new channel in a direct messages and it looks like he is allowed to buy it. However funds are not send to the user that posted an offer and after refreshing app information that funds has been send disapears from buyers app. 

Platform: Mac posting - Windows buying 

Steps to recreate:
- post an offer from Mac with required shipping info
- another user using Windows should buy an offer
- check if payment was successful (right now it's not working if Mac is posting and Windows is buying. Other way around - it's working as expected)

**Comment by NorbertBodziony** [comment]
I think it is caused by crashing/slow cli (Creating transaction may take a lot of time). Cli is way faster in next version i think it will fix this issue.

**Comment by NorbertBodziony** [comment]
I will make it as done but to check in next QA run.

**Comment by kingalg** [comment]
Working on both systems.
