### ISSUE TITLE
Tor messaging should be enabled by default for new users (and we should inform users of this) 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#539]
It seems to be working well, so let's enable it by default. 

Before closing this ticket, we should review the website and intro slides in Zbay to see if we mention Tor anywhere, and include a mention of it. Assign to hw when complete)

**Comment by holmesworcester** [comment]
We may want to send this in the same tx as the username registration, just as a separate output. We don't want to lock up UTXO's or create delays.

**Comment by vinkabuki** [comment]
Now, whenever you are sending DM, you'll be notified if you are sending it through tor or zcash. Kinga says that there is no mention about tor in slides, should we consider this ticket done after adding this information to intro slides?

**Comment by kingalg** [comment]
Slides are a new issue #602 
In theory - it's working. Tor is turn on in Settings from the start, users are informed about it if a second user in direct messages is using tor as well.
In practice - we have a lot of bugs related to this functionality. @holmesworcester should we consider this one generally "done" and focus on bugs in different tasks or wait with closing this until this part is working without bugs?

**Comment by holmesworcester** [comment]
We should make issues for specific issues and prioritize those separately. This issue is about whether it's enabled by default for new users.

**Comment by kingalg** [comment]
In a new version information if the user is connected via Tor or Zcash is missing from the screen. It was there in the previous version and is still there on Windows so I assume that this was implemented but we have some bug.
