### ISSUE TITLE
Error message (I think caused by Tor messaging user disconnecting)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#540]
This error message happened right when Norbert was saying he had to go, so it may correspond to one user signing off. 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/213678/97481516-511bda00-192b-11eb-93a9-e39f38d1f77f.png">

**Comment by holmesworcester** [comment]
@kingalg we should add QA workflow items for "other user disconnects / reconnects / etc" to cover issues like this.

**Comment by kingalg** [comment]
Problem is still there on 24 November 2020.

**Comment by holmesworcester** [comment]
Closing because we really can't reproduce this. And it may be fixed.
