### ISSUE TITLE
Funds appear to be received but nothing displays in UI

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#544]
What happened:

0. I'm fully synced
1. A user sent funds to a z-address
2. My balance increased, so funds appear to be received.
3. Nothing new appears in "unknown" 
4. No notification or indication in the UI at all.
5. Only previous transactions display in unknown
6. Tried again and same thing happened.

TXIDs:
1. ea86954b76a9c25536edd6476a10050c6fce145b08be138da945c04307cf2b4b
2. d86a91ef812567c843d6490ea5ba966ca20e036499bbf14939b4c5eed2643350

**Comment by NorbertBodziony** [comment]
It works fine. Only case it will not work if you send transaction to yourself but thats edge case.

**Comment by holmesworcester** [comment]
I’m still seeing this in my current version. 

Expected: I see the funds in the “unknown” tab. 

Actual: I see no funds in that tab. 

Note that I see some test funds that Kinga has sent me from zecwallet that *have* a memo. But I do not see any funds that do not have a memo.

**Comment by kingalg** [comment]
This task is still valid. I've created https://github.com/ZbayApp/zbay/issues/684 for the same issue but now I'm closing 684 as duplicated with this task.
