### ISSUE TITLE
Logs section is now empty, so we should remove it. 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#545]
There aren't any logs in zbay lite so we should remove this section.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/213678/97647588-054f5a80-1a29-11eb-8ee2-0f4277bf1cb3.png">

**Comment by holmesworcester** [comment]
We can remove this link to it.

<img width="35" alt="image" src="https://user-images.githubusercontent.com/213678/97647610-10a28600-1a29-11eb-8fe6-42a83e073f2a.png">

**Comment by vinkabuki** [comment]
Done, removed both section and icon. Also cleaned all related code to this in codebase.
