### ISSUE TITLE
Zbay should save messages sent and received via Tor (all messages)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#546]
Right now when messages are sent via Tor they disappear on shutdown. We should save them.

**Comment by holmesworcester** [comment]
The way we're planning to do this is to save the entire application state and rehydrate on restart. 

How frequently will it update?

**Comment by holmesworcester** [comment]
If this starts to look like a complicated way to achieve the goal of this ticket, let's discuss again.

**Comment by holmesworcester** [comment]
Bonus: if user can start right up with no delays, that's great.

**Comment by NorbertBodziony** [comment]
Saving messages is done and merged in next release. I will look into making startup faster.

**Comment by NorbertBodziony** [comment]
This can also allows us to remove electron-store but i will leave it as separate task.

**Comment by holmesworcester** [comment]
Question: how synced do you have to be in order for your sent transaction to not expire?  Let's set to a safe value for *that*.

**Comment by holmesworcester** [comment]
Also, "pending" might not show until you are synced, if you send when you are behind. @kingalg should check to make sure that "pending" state appears properly after leaving the app for a few days to get up to the threshold of blocks behind but not past it.

**Comment by holmesworcester** [comment]
Let's set to 2000 now and check.
