### ISSUE TITLE
Two direct message channels opens for one offer

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#553]
When the user want's to buy an offer or ask a question about it new channel should be created under direct messages. Currently TWO new channels are created - one after the user choose "message" button in an offer and second one after he choose "buy" button. This only happens on MacOS.

![Screenshot 2020-11-03 at 02 04 42](https://user-images.githubusercontent.com/68909168/97972928-2641e380-1d7a-11eb-9654-f63db04aba11.png)

**Comment by NorbertBodziony** [comment]
This looks like state management issue we are changing redux so maybe one of selectors is still incorrect that why its happening.

**Comment by kingalg** [comment]
It's working now.
