### ISSUE TITLE
Tor messaging doesn't work on Mac for some users (Jason error)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#554]
It seems that Tor is missing a dependency.

**Comment by NorbertBodziony** [comment]
@kingalg please check it on next release.

**Comment by holmesworcester** [comment]
Tor messaging is still not working for me sometimes in the latest release. I don't think this is done.

**Comment by NorbertBodziony** [comment]
I will need more details is first message timedout ? Or tor does not spawn ?

**Comment by holmesworcester** [comment]
Tor was running, but message went via Zcash. 

Latest theory is that I didn’t have the other user’s address registration yet. So they could message me but not vice versa.

**Comment by NorbertBodziony** [comment]
That's possible also sometimes the first message will go via zcash because of timeout. Its currently 8 sec but it can even take like 20 sec to get connection sometimes.

**Comment by holmesworcester** [comment]
I think the issue we discovered with the registration channel not being
snapshotted could also be a factor.

**Comment by NorbertBodziony** [comment]
Snapshot created.

**Comment by kingalg** [comment]
As we've discovered what could be a reason and I wasn't able to recreate it after consultation with Norbert I'm closing the issue.
