### ISSUE TITLE
Can't install zbay on freshly installed Windows

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#557]
Installing zbay (any version) on a fresh system (Windows, 64 bit) results in JavaScript error and makes instalation impossible.

![image(1)](https://user-images.githubusercontent.com/68909168/98554910-903e1980-22a1-11eb-89f4-e4e694d47a9f.png)

**Comment by kingalg** [comment]
@NorbertBodziony in the office you have one of the laptops on which this problem occurs. Feel free to use it for tests if you can't reproduce it on your computer.

**Comment by NorbertBodziony** [comment]
@kingalg Last version worked smooth so i guess its done ?

**Comment by vinkabuki** [comment]
Kinga successfully installed zbay on windows today and this errror is probably related to someone mistake in the past and trying to use index.node that was not build on windows, I consider it's done.
