### ISSUE TITLE
Status icon overlapping with "unknown"

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#574]
Status ikon adjacent to the "unknown" in side panel is overlaping with the letters. As "unknown" doesn't need any status I sugest removing this ikon. 

System: Windows, MacOS

![Capture2](https://user-images.githubusercontent.com/68909168/100087735-6fec8e00-2e4f-11eb-876e-d148f46c4fd0.PNG)

**Comment by holmesworcester** [comment]
Agreed. We can remove it, especially since these unknown icons are somewhat meaningful.  @NorbertBodziony how is status being determined now?

**Comment by holmesworcester** [comment]
Adding blocks release because this looks broken and seems trivial to fix. If not trivial let's skip.

**Comment by NorbertBodziony** [comment]
On start we check if user is online and try to connect. Also if you send message to somebody we check if he is online.

**Comment by holmesworcester** [comment]
if somebody tries to connect to *you* on startup, and they’re successful, will they show up as online? will we connect back to someone when they connect to us?

**Comment by NorbertBodziony** [comment]
Yes icon will be green. We are not connecting back since we do not know who connected to us.

**Comment by kingalg** [comment]
@holmesworcester It's not overlaping any more hovewer thare was a misunderstanding about the icon:
- I thought that we will be removing status ikon for "unknown"
- Norbert thought that status ikon is staying and we are removing the other ikon
Which one is correct?

Right now it's not overlaping any more and it's more of a disign problem so I'm removing "block release" tag.

![image](https://user-images.githubusercontent.com/68909168/100233404-00979c80-2f2a-11eb-88f8-98f00bb91c69.png)

**Comment by holmesworcester** [comment]
I think we should keep the existing unknown icon, since the online status won’t exist for unknown.

**Comment by kingalg** [comment]
In the end, it looks like after some time we've ended up with the wrong icon for the unknown.
