### ISSUE TITLE
Problems with funds send on z-address

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#577]
Some of the funds send on z-address are not send (but tx ID is generated and included in the block, eg txid: 120de8eb10a4f7b95402d5a2ebafc623b5e4242c3cfadb45f77eb8fe2baabc90) 

Platform: Windows, MacOS

**Comment by holmesworcester** [comment]
@kingalg you mean they're not received? 

or you mean a transaction is sent that isn't a valid one?

**Comment by holmesworcester** [comment]
If you send money, does your balance go down? @kingalg

**Comment by kingalg** [comment]
It's working in v2.2,4
