### ISSUE TITLE
JavaScript error after changing to tor

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#578]
After changing method of messaging on MacOS from Zcash to Tor I've tried to send direct message and javascript error occured (message reached the other user).

![Screenshot 2020-11-25 at 14 20 41](https://user-images.githubusercontent.com/68909168/100235343-96342b80-2f2c-11eb-856e-a357ee7583f7.png)

**Comment by holmesworcester** [comment]
Error messages should be release blockers I think. @kingalg

**Comment by kingalg** [comment]
Duplicated with 540 (https://github.com/ZbayApp/zbay/issues/540)
