### ISSUE TITLE
Clicking on OS notification should take you to the channel / DM 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#581]
Right now when you click on an OS notification it takes you to Zbay, but it should open the thread or channel where the notification "came from" if you haven't opened it yet. 

Steps to reproduce:
1. click away from a conversation and wait for a OS message notification 
2. click on notification

expected: conversation opens in Zbay
actual: Zbay in foreground but on a different conversation

**Comment by kingalg** [comment]
It's working in a ve 3.2.6.
