### ISSUE TITLE
Fee shown in text entry field doesn't appear to be correct

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#588]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/213678/100747015-7c249e00-33af-11eb-8043-6733148c38c8.png">

We increased the fee 4x and I don't think the $0.0002 has changed at all. This number should be generated dynamically based on exchange rate and the actual current fee that we are using.

**Comment by kingalg** [comment]
I can see different fees now.
