### ISSUE TITLE
Error sending message "check node connection"

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#597]
I was so excited about improved performance, but maybe my zecwallet-light-cli was just dead?

<img width="743" alt="image" src="https://user-images.githubusercontent.com/213678/101688149-97d81600-3a39-11eb-97db-b8462994e9df.png">

Do we know why this happened?

**Comment by vinkabuki** [comment]
Have you tried `Try again`? What happened?

**Comment by holmesworcester** [comment]
yes. it tries again and the same error happened.

**Comment by holmesworcester** [comment]
Just got this error, clicking retry after restart.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/213678/101804470-9cefa080-3adf-11eb-9efd-a7b0de5db94b.png">

**Comment by holmesworcester** [comment]
and then i got an error clicking “send and restart” i.e. an error sending the error message! :/

**Comment by holmesworcester** [comment]
And then clicking "yes" appeared to do nothing, here. and then I got a js error.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/213678/101804662-d9230100-3adf-11eb-81dc-afb952892622.png">

**Comment by vinkabuki** [comment]
It looks like try again handler is buggy, I will give update on this soon.

**Comment by holmesworcester** [comment]
I think I know what's happening here @vinkabuki:

1. When Zbay is not synced, this error will display, because Zcash needs to be synced within N blocks of the chain height to create transactions, and I think N is small, like 10. 
2. Zbay does not resume syncing again on wake from sleep. 

I'll create two separate issues for these.

**Comment by holmesworcester** [comment]
likely not an issue anymore, given removal of zcash for messaging.
