### ISSUE TITLE
Tor is still running after quit

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#598]
Steps to reproduce:

1. run Zbay on macOS 10.15.7
2. quit

expected: tor process stops
actual: tor process still running

Side thought: is it worth re-naming the binary "zbay-tor" or something like that so that it's clear what process started it, and distinct from "normal" tor running on the user's machine?

**Comment by vinkabuki** [comment]
cannot reproduce on linux, gonna check this on Kinga's Mac today during QA

**Comment by vinkabuki** [comment]
Is that always happening to you? Or just in case unexpected close like getting error and close?

**Comment by holmesworcester** [comment]
I was getting errors on close a lot, so it could have been that. 

right now i’m not getting errors on close and tor is shutting down properly for me.

let’s mark this fixed for now.
