### ISSUE TITLE
Lag in UI (e.g. text area while typing messages, sidebar while switching channels)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#599]
There's a pretty significant lag in the text area while typing messages, and I also notice it a lot when switching channels in the sidebar. Sometimes the frontend freezes up. 

It feels pretty consistent with the problem of blocking the main process or blocking the renderer process:

* https://www.electronjs.org/docs/tutorial/performance#3-blocking-the-main-process
* https://medium.com/actualbudget/the-horror-of-blocking-electrons-main-process-351bf11a763c

**Comment by vinkabuki** [comment]
Laggy input is related to heavy and often re-rendered components.

**Comment by vinkabuki** [comment]
Do we need all zbay users here? Is it practical to be able to mention every user? Maybe reduce it to just contacts? What you think?

![image (1)](https://user-images.githubusercontent.com/30016150/102112590-34cef080-3e38-11eb-87a1-25d4d5edf40d.png)

**Comment by holmesworcester** [comment]
We could change it to just users who have spoken in the channel but in the
zbay channel that won't work as well.

How about just people who have spoken in the channel and the last n people
who have joined (20?)

**Comment by vinkabuki** [comment]
Honestly I was hoping that this is cure for laggy UI. It isn't, maybe let's create another issue for this because it's a good idea at all but at this moment not related with laggy input that much.
