### ISSUE TITLE
Missing information about funds sent to shielded address on Mac

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#603]
Missing information about funds sent to the shielded address on Zbay on mac. 

Funds sent to Zbay on MacOs to the shielded address are received but information about that fact and any additional text sent with funds are missing.

**Comment by kingalg** [comment]
@holmesworcester @vinkabuki I know that Bartek didn't had a chance to have a look at this one but I think that he might fix it with something else. I don't have this problem in the 2.2.6 version.

**Comment by holmesworcester** [comment]
if it’s working for you let’s close!

**Comment by vinkabuki** [comment]
It's working with the newest version - checked on macincloud

**Comment by vinkabuki** [comment]
closing
