### ISSUE TITLE
Fix faucet 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#618]
Zcashd is failing now and has been generally unstable. We need to fix the faucet.

Options: 

# Move from zcashd to zecwallet-light-cli

We can avoid exposure to this long term, and fix our short term problem, by switching the faucet to using zecwallet-light-cli.

* The faucet should send Zcash when Zbay pings it.
* The send should guarantee that the user has the desired starting number of utxo's (10? 20?) so that they can send multiple transactions without running out of UTXOs. Perhaps this can be achieved by including the same address multiple times as an output.
* This should happen quickly, e.g. the zecwallet-light-cli should already be synced or close to synced.

# Fix Zcashd

* Get support from ECC team
* Figure out what the issue is
* Fix

**Comment by vinkabuki** [comment]
I've split the UTXOs on each address, so now each address has +/- 20 UTXO, I've also added logic to automatically split UTXO until each address has 50 UTXO
