### ISSUE TITLE
Dates not appearing properly in messages view

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#623]
You can see in this screenshot in the #zbay channel that there are no date dividers, and that times span multiple days without any date dividers. This is in the public release of Zbay, not the pre-release version for testing. 

<img width="902" alt="image" src="https://user-images.githubusercontent.com/213678/103779160-58352780-5001-11eb-9d9c-d34f0fd0b314.png">

**Comment by kingalg** [comment]
Dates are actually there but in the top of the channel and they are starting with Friday, Jan 1. All messages from the previous year are in bulk under "Invalid DateTime". 

![obraz](https://user-images.githubusercontent.com/68909168/103780181-f1316600-5034-11eb-9c61-6e742ad6e65a.png)
