### ISSUE TITLE
Users should be able to send and receive messages on public channels fast, using libp2p

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#625]
There are a series of tickets that (I think) can only be tested and released as a group, so this meta ticket makes sense.

Here are the individual tasks:
https://github.com/ZbayApp/zbay/labels/libp2p

These have the priority of this ticket. Anything higher priority than this ticket should come first. 

@jkdev601 is there a ticket created for making sure that Tor and Git support work across all platforms?

**Comment by kingalg** [comment]
Right now, I'm not able to send any message on public channel at all but I can see that it's not true to all users of this (3.2.4) version.
