### ISSUE TITLE
Add logic to wait for windows defender to check files before access config file

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#632]
When changing messaging from tor to zcash below error ocured. 

Solution: Add logic to wait for windows defender to check files before access config file.
That's probably super edge case, but there is possibility that zbay will try to modify the config file, while it's checked by windows defender

![image(6)](https://user-images.githubusercontent.com/68909168/105038449-9e59a480-5a5f-11eb-8b87-1fba9cbe9995.png)

**Comment by holmesworcester** [comment]
this has to do with zcash messaging, right? @vinkabuki 

can we close?
