### ISSUE TITLE
User should be able to register a username before they receive any Zcash

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#633]
Problem: right now username registration is slow and confusing, because users have to wait to receive Zcash and then send it to register, which takes several minutes. 

Solution: we should send the registration message ourselves, and the app should notify the user when it confirms that registration was successful. 

If the username is already taken, the user should see an error.

**Comment by kingalg** [comment]
There is an error if a username is taken and a green confirmation message when the registration is successful. Right now everything is working smoothly with registration.
