### ISSUE TITLE
Zcash stops syncing after sleep

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#654]
Steps to reproduce on Mac:

1. Start Zbay
2. Sleep computer e.g. by closing laptop lid.
3. Reopen 

Expected: Zbay syncs to latest block
Actual: Zbay never syncs

Ideal behavior:

1. Zbay upon waking up immediately changes synced status to "--%"
2. Zbay quickly discovers what the latest block is and displays the correct latest block and percentage
3. Zbay syncs, and the numbers update as it syncs. 

UPDATE: we'll spend 2 hours investigating this and then discuss if we need to go farther.

**Comment by vinkabuki** [comment]
@holmesworcester Is that happening to you every time? I've reproduced this on windows but only once

**Comment by holmesworcester** [comment]
i think so, yes. i’ll try the steps you suggested.

**Comment by vinkabuki** [comment]
Normally, you should see these logs 'info' and 'info 2' every 30 seconds. @holmes could you check this if you have chance? it should look like this
![syncing](https://user-images.githubusercontent.com/30016150/111295988-451b8500-864c-11eb-9334-95da8d192a36.png)
