### ISSUE TITLE
All Zbay files should be in a Zbay folder in a standard location, not scattered everywhere

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#658]
On Mac we are storing things in Library/Application Support/Zbay. This would be the best place. 

We should use the same folder where we store other Zbay stuff, and follow OS conventions where possible

Ideally we would store all Zbay files, including:

1. zecwallet-light-cli files currently stored in the Zcash folder, which is shared with Zecwallet. 
2. All Tor files

It's possible that the zecwallet-light-cli files are in a hardcoded location. If so, we should change the location in our fork (we're using a fork, correct?) and submit an issue to zecwallet-light-cli to let us change file locations by passing some parameter on startup. (We may have created an issue for this in the past.)

**Comment by kingalg** [comment]
Right now to successfuly uninstal Zbay user should follow path as below:

Uninstalling Zbay and removing all tor/zbay related files on MacOS:
1. Move to bin - Zbay app from Applications
2. Move to bin - Zbay folder from Users -> USER ->Library -> Application Support
3. Move to bin - zbay_tor folder from Users -> USER
4. Move to bin - torrc from Users -> USER
5. Move to bin - zecwallet-light-zbay-wallet.data and zecwallet-light-zbay-wallet-debug from Users -> USER -> Library - Application Support - Zcash (if you have Zecwallet on the same computer be careful as Zbay and Zecwallet are sharing Zcash folder. Removing the whole Zcash folder, in this case, would break Zecwallet).
6. Move to bin - .tor from Users -> USER (it’s hidden so you can either remove it using terminal or go to the file and Hold down the Command, Shift and Period keys: cmd + shift + [.] to see unhide files)
After removing the above files please restart your computer.
For testing purposes - it is best to create a new account on mac and test the next version.


Uninstalling Zbay and removing all tor/zbay related files on Windows:
1. Double click on the Uninstall Zbay icon from Users -> USER -> AppData -> Local -> Programs 
2. Delete - tor folder  from Users -> USER -> AppData -> Roaming
3. Delete - Zbay folder  from Users -> USER -> AppData -> Roaming
4. Delete - zecwallet-light-zbay-wallet.data and zecwallet-light-zbay-wallet-debug  from Users -> USER -> AppData -> Roaming -> Zcash  (if you have Zecwallet on the same computer be careful as Zbay and Zecwallet are sharing Zcash folder. Removing the whole Zcash folder, in this case, would break Zecwallet).
5. Delete zbay_tor folder from Users -> USER 
6. Delete torrc from Users -> USER 
After removing the above files please restart your computer.
