### ISSUE TITLE
Messages appear in incorrect order (timezone issue?)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#664]
Note that a message is showing up as being sent in the future. (it's still friday here)

@vinkabuki can you see anything in the message data that would indicate why this is happening? 

<img width="504" alt="image" src="https://user-images.githubusercontent.com/213678/107840333-e9758780-6d7f-11eb-83b9-b28f23e26fec.png">

**Comment by vinkabuki** [comment]
It looks like it's timezone issue, portroni has bigger timestamp, quick fix for public channels is to sort messages by blockheight. I think we should add timezone detecting, or let user choose timezone on registration and create timestamps based on this. I've checked and right now we don't do this, so timestamp is based on your local time, so messages from future are possible.

**Comment by holmesworcester** [comment]
we should figure this out when we move to orbitdb, since that change will happen in weeks.

**Comment by holmesworcester** [comment]
Update: message ordering will be solved out-of-the-box by orbitdb. That is, orbitdb will determine the order messages are shown in, and it includes some safeguards for messaging ordering. See: https://github.com/orbitdb/ipfs-log

However, timestamps will still be an issue. 

Created https://github.com/ZbayApp/zbay/issues/714 to track this. Closing this ticket.
