### ISSUE TITLE
Users can't send messages to online Tor contacts without funds

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#670]
Steps to reproduce:

1. Have zero funds (either a fresh start, or by spending all your funds)
2. Try to send a message to another online user (a user with a green circle next to their name, e.g. yourself on another machine) using Tor. 

Expected: a message field is available, and you can send a message, despite not having funds.

Actual: the message field will not display if you don't have funds, and you cannot send the message. 

Right now if you don't have funds you can't send messages to a Tor contact even if they are online.

**Comment by kingalg** [comment]
I've checked it and it's working now.
