### ISSUE TITLE
New users should start in a DM thread with holmes, so they can chat immediately.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#679]
Right now, users start in the #zbay channel, which is a bit overwhelming, might not be high quality since we use it for testing a lot, and won't let them send messages. 

Users should start in a thread with me (@holmes). It can look like this:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/213678/108578923-9311c700-72f2-11eb-8986-55856b5935b8.png">

https://www.figma.com/file/hyyvxEFONwoNOHk82bk6sq/Registration?node-id=12%3A1368

We should hard code the first messages in the thread, to the time of onboarding. 

I'll provide text for these messages here.

I'll also set up a laptop and leave it on all the time, so that I'll pretty much always be online (though I might not always respond immediately.) 

Messages have timestamps, and these should be set to the current time at onboarding, I think. (If this is hard, we can leave out the timestamps)

## Text

There should be four messages, or one message if you can get the linebreaks and it looks better. The link should be linkified, and the channels #zbay and #store should be clickable links to the respective channels (this is how they'd typically be formatted.)

------

Hi! My name's Holmes. I'm an activist. I used to co-direct the organization https://fightforthefuture.org, which sort of saved the Internet, multiple times I think? Now I'm making Zbay!

Our goal is a team chat space like Slack or Discord, but with no central server that can leak a team's entire chat history (including the mortifying parts) all over Google in an instant.

Zbay is janky / confusing sometimes 🤦‍♀️, but DMs work okay, and once you have some Zcash (we're sending some now) you can can say hi on #zbay and #store! 🎉

Or try messaging me here! If I'm away I'll be back soon. Questions? Annoyances? Any burning needs where, if Zbay met them, you'd use it every day? I'd be so, so grateful to hear from you!

**Comment by kingalg** [comment]
We have slightly different emoticons (with the same meaning). It's working as expected on both Mac and Windows.
