### ISSUE TITLE
Make waggle easier to work with

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#683]
We discussed making it easier to use an instance of waggle that's running in the background, so that you don't have to restart zbay every time.

**Comment by holmesworcester** [comment]
@EmiM @vinkabuki is this still an issue now that zbay is faster to restart? 

@kowalski what would you like to do here?

**Comment by EmiM** [comment]
It is connected or duplicate of https://github.com/ZbayApp/zbay/issues/755

**Comment by holmesworcester** [comment]
kowalski says: renderer would try to connect to waggle in a robust way, and would connect as soon as waggle was available. 

emi says this is a duplicate, so I'm closing.
