### ISSUE TITLE
Can not not send direct messages via Zcash

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#691]
All messages are working correctly when Tor is open but when in Security we change Tor for Zcash there is an error when user want to send direct message.

System: MacOs, Windows
Version: v 2.2.11

Steps to recreate:
1. Open "Seurity".
2. Change default "Tor" to "Zcash".
3. Try to send direct message to the other user.

![Screenshot 2021-03-09 at 17 00 53](https://user-images.githubusercontent.com/68909168/110499947-02f8bd80-80f9-11eb-8c93-f3454da90b6f.png)

**Comment by vinkabuki** [comment]
I've deleted lightd.main.zcashfr.io and shielded.nighthawkwallet.com nodes, since I can't reproduce this bug, I am moving this to QA, but without 'done' label.

**Comment by kingalg** [comment]
It's working on my freshly installed v 2.2.11 with a few fixes.
