### ISSUE TITLE
User should be able to send holmes a message almost immediately

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#701]
Right now a first time user can't send holmes a message.

They should be able to immediately or almost immediately on startup. 

It's okay if holmes can't reply, or if replying causes a crash. We will fix those later.

**Comment by vinkabuki** [comment]
Hi, quick annotation to the first issue: user will be able to send message to holmes as soon as he connects to waggle and fetches waggle users

**Comment by kingalg** [comment]
This may be fixed but we don't have a way to check this in version 3.2.14 as there are waggle problems. To be moved to "ready for qa" with general waggle fix.

**Comment by kingalg** [comment]
Moved back as per comment from an hour ago.
