### ISSUE TITLE
Users should be able to send direct messages via waggle

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#708]
Right now Tor messaging only works when users are online. 

We can use waggle to let people send direct messages even when offline. These will have to be stored by other users in the team, which won't scale for very large teams, but that's okay.

At some point we can do a hybrid approach and send directly when users are both online, but right now it seems best to consolidate everything around waggle, for simplicity and stability. 

Our default plan for how this would work is to create a hidden channel for direct messages, post all messages to that channel, and encrypt them. 

(This sacrifices some of the integrity protections that orbitdb offers for message ordering, e.g. and we can consider alternatives, but I think this is our starting point.) 

Our default plan is to use zecwallet-light-cli for this since that works with existing zcash keys. But we can also use a js crypto library. 

We should protect against replay attacks. That is, someone with access to the orbitdb of encrypted messages should not be able to pick messages, resend them, and have them appear as new messages sent by the original sender.

We should also encrypt the metadata so that it is not possible to know the sender or the recipient. 

Every user will attempt to decrypt all messages on this channel to see if it's addressed to them.

**Comment by holmesworcester** [comment]
@kingalg please confirm that this fixes #702, #700 and #674

**Comment by kingalg** [comment]
> @kingalg please confirm that this fixes #702, #700 and #674

@holmesworcester  confirmed that they are resolved. I assigned them to a project and closed them.
