### ISSUE TITLE
Replace entry node with a tracker for initial peer discovery

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/zbay#722]

**Comment by holmesworcester** [comment]
Some requirements for this:

1. Client connects to the tracker via Tor, so we don't leak the relationship between someone's Tor address and their real IP.
2. We must connect via HTTPS, so that a malicious Tor exit node cannot impersonate the tracker. 

Also, I think we're adding this mostly as an intermediate step to solving this problem generally for all communities, and then shipping the app with a hardcoded community.

**Comment by kowalski** [comment]
@holmesworcester 

> We must connect via HTTPS, so that a malicious Tor exit node cannot impersonate the tracker.


For this to protect us we must generate SSL certificate for the tracker with some rootCA that everyone agrees on.
If this certificate is self-signed, than a malicious Tor exit node would just create own certificate.

I think the right moment to add this is when we will do the PKI certificates for members of community. This will provide us with the RootCA that we can use for verification. What do you think?

**Comment by holmesworcester** [comment]
I think it's best to pin the cert in the app, correct?

**Comment by kowalski** [comment]
The app is opensource. If someone would want to impersonate tracker he
would take certificate from the code.



pt., 26 mar 2021, 17:15 użytkownik holmesworcester ***@***.***>
napisał:

**Comment by EmiM** [comment]
https://github.com/ZbayApp/waggle/pull/12
Tracker code is merged but changes are not being used yet (we need to fix current problems first) so nothing changes.

Notes: 
- remember to keep current db in at least one of the regular peers before deploying. This may be obvious but keep in mind that after removing the entryNode there will be no "proxy" to keep our db backed up so if we all remove our DBs for testing purposes, the data will be gone. 
- the connection goes through http, not https. The tracker is very basic and will be rewritten anyway when we start implementing communities. 
- default peerExpirationTime is short (2 hours) so we may want to change that :)
 
Turning on the tracker requires two steps:
* Uncomment tracker-using code (connectionManager.ts, Dockerfile)
* deploy tracker to aws (just as it was done with entrynode)
We can do it as part of this task: https://github.com/ZbayApp/zbay/issues/777
