### ISSUE TITLE
Remove "add funds" tooltip because user doesn't need to add funds

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#727]
Right now there is a prominent "add funds" tooltip displayed on startup, pointing to the "add funds" link. 

This no longer makes sense now that we are sending each user funds, and it's very distracting. 

We should remove this tooltip.

**Comment by holmesworcester** [comment]
@kingalg is this done already? i think it may be. if so can you close?

**Comment by kingalg** [comment]
I'm re-opening this as in a version that I've got on 05/05 it's an issue again.
