### ISSUE TITLE
Too many Tor connections

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#737]
I see this error in terminal:

```Mar 30 07:42:39.000 [notice] We'd like to launch a circuit to handle a connection, but we already have 32 general-purpose client circuits pending. Waiting until some finish.```

This leads me to believe that if my Tor tries to make too many connections I'm going to have a problem.

Not sure what the solution should be but this is probably causing general unreliability.

Can we time out Tor connections faster, for non-critical things like online status indicators?

UPDATE: I think this leads to Zbay not being able to send waggle messages, if you have too many direct message contacts.

**Comment by vinkabuki** [comment]
Disappeared after removing DMs, closing
