### ISSUE TITLE
Users should not have to click "sign in" or "continue"

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#739]
Previously we let users choose when the app connected to the internet, in case they wanted to enable tor. 

Now I think it's not worth the extra click and delay. 

We should remove this initial screen for first time and returning users, and go straight into the "fetching channels..." loading spinner.

**Comment by holmesworcester** [comment]
@kingalg @Dinek007 this is done and released, right?

**Comment by Dinek007** [comment]
right
