### ISSUE TITLE
Scrolling backwards through old messages should be comfortable.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#745]
Our previous solution to scrolling back through old messages was not a great one.

We should look at what Slack and Discord or other infinite scroll schemes do in this case and do something standard.

I think what happens is you scroll back into "blank" which then gets filled in as you scroll. Sometimes the blank areas are filled with some kind of placeholder image.

Another approach is to load quite a lot of messages at a time and show a spinner. WhatsApp and Signal do this. 

We should consider "quick fix" approaches to this for now, and creating more elaborate tickets later.

**Comment by holmesworcester** [comment]
related #744

**Comment by EmiM** [comment]
This can take a little bit more time than expected because the proper logic has not been implemented yet.
Also I am replacing library for scrolling because current one is dead (last time published in 2017) and can blow up when we'll try to upgrade other parts of the system. Fortunately people created 2 independent libs based on this one and I will use the one with more weekly downloads. Replacement is instant because the new lib is backward compatible.

**Comment by holmesworcester** [comment]
for keeping a handle on the time and complexity, what shortcuts are available to us? are there any that seem like they make sense to you? can we load many (or all?) messages once someone starts scrolling back, and unload them again when they switch to a new channel?

Can we load all messages after a user loads the first messages of a channel? 

What’s the laziest/simplest we can be without impacting performance?

**Comment by EmiM** [comment]
https://github.com/ZbayApp/ZbayLite/pull/244
I put the scroll handle to the bottom and I thing scrolling up behaves slightly better (it's still DEFINITELY not perfect). However there is one downside - channels with small amount of messages have messages rendered from the top:
![Screenshot from 2021-04-29 18-32-21](https://user-images.githubusercontent.com/6099829/116586743-161a5380-a91a-11eb-915a-d1da50638ed2.png)

If that's something we can live with temporarily then we could test it and merge the changes.

**Comment by holmesworcester** [comment]
Looking forward to trying it out! Seems like this counts as a fix!
