### ISSUE TITLE
JavaScript error on Mac for fresh install v 3.2.3

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#746]
The user (not every but it happened to me three times in a row) gets JavaScript error on a fresh install of zbay 3.2.3. It hapened after some time. It mostly prevent a user from using zbay hovewer on one of the bugged version after a few hours the user was registerred and I could use zbay without problems. 

Steps to recreate:
1. Install new zbay version 3.2.3 on a clean account
2. Wait for an error to apear

![Screenshot 2021-03-30 at 15 12 56](https://user-images.githubusercontent.com/68909168/113029013-3d9bc600-918c-11eb-9042-c2428fe6328d.png)

**Comment by vinkabuki** [comment]
every 15 minutes, zbay is checking if there is update - sometimes there is problem with network, it's related to electron builder, other users also experience this, It's not that serious, it's like skipping update check, I'll try to somehow handle this error so users don't get this js error window
https://github.com/electron-userland/electron-builder/issues/2398
