### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#750]
User receives multiple notifications

**Comment by EmiM** [comment]
https://github.com/ZbayApp/waggle/pull/14 <- this fixes the problem with same multiple notifications. 

Also I noticed that if I am 'anon' I receive notifications about my own messages.

**Comment by kingalg** [comment]
It's still a problem, I'm moving it back to backlog.

**Comment by EmiM** [comment]
@kingalg does it still occur in version 3.2.6?

**Comment by holmesworcester** [comment]
kinga says it seems to be fixed.
