### ISSUE TITLE
Zbay can be faster at fetching orbitdb messages

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/zbay#751]
Pulling messages slows app. It's because each pull calls add_message action for every message. We should convert it to add all messages to store at once or pull messages differently

**Comment by EmiM** [comment]
I think pulling messages in a loop is not necessary. I did it before implementing other fix
https://github.com/ZbayApp/ZbayLite/pull/223
We could also use 'replicate.progress' for sending single messages to zbaylite (currently we send all messages for channel on each 'replicated' event): https://github.com/ZbayApp/waggle/pull/17

**Comment by holmesworcester** [comment]
@EmiM so this is affecting both pulling older messages *and* receiving messages right when they are sent, correct?

**Comment by EmiM** [comment]
Yes. I was thinking if we could use `replicate.progress` event but now I'm worrying what if a message gets lost between waggle and zbaylite. That's why I decided that setting all messages at once to redux store will be good enough for now.

**Comment by EmiM** [comment]
https://github.com/ZbayApp/ZbayLite/pull/230
https://github.com/ZbayApp/waggle/pull/20
