### ISSUE TITLE
Reopening Zbay on macOS disconnects waggle making public channels unusable

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/zbay#754]
How to reproduce:
* open Zbay, sign in
* write something on public channel - writing should work properly
* close the app using X on the top left corner
* reopen the app by clicking on Zbay logo on the dock
* Zbay opens (one has to click "sign in" button but I don't think it should be like that)
* now sending messages on public channels doesn't work (message disappears after user hits enter)
It's probably because Zbay lost a connection to waggle while reopening.

**Comment by holmesworcester** [comment]
Seems like 'X' should quit, for now.

Removing 'blocks release' given how much we're doing with this release, and given that cmd-q and "file > quit" still work fine.

**Comment by holmesworcester** [comment]
The way it's supposed to work is:

- red X closes window 
- waggle doesn't stop running
- clicking doc icon creates new window
- waggle still works

If this is harder, making 'x' quit the app is fine.

**Comment by EmiM** [comment]
https://github.com/ZbayApp/ZbayLite/pull/222 <- this may be the temporary fix (quitting app completely on X) but I have to test it first

**Comment by EmiM** [comment]
Tested on mac os. 
Proper fix (reconnecting with waggle) will be available after implementing reconnecting (#755)
