### ISSUE TITLE
Users can still post offers, but it's not working yet (disable it)

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#758]
Offers posted on public channels are visible by the user that posted an offer but not for the rest of the users on channel.

Systems: Windows, MacOS

Steps to recreate:
1. Join public channel
2. Post an offer
3. Check if the offer is visible by another user

**Comment by EmiM** [comment]
How did it work before? Should it be saved and sent as a message and displayed later in channel history?

**Comment by holmesworcester** [comment]
We're going to change how these work since there's too much complexity here to carry forward. 

For now, I think the best solution is to remove the "offers" functionality completely.

**Comment by holmesworcester** [comment]
We could remove the "shipping address" settings screen as part of this, too.

**Comment by holmesworcester** [comment]
@Dinek007 so you'll fix this? is this done?
