### ISSUE TITLE
Developers should be able to run production Zbay and their development Zbay on the same machine, with separate accounts.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#762]
Options:

1. Change folders so they don't conflict.
2. All devs run Zbay in a VM.

**Comment by holmesworcester** [comment]
This looks like an ok way to do it: https://medium.com/@SaravSun/running-gui-applications-inside-docker-containers-83d65c0db110

**Comment by holmesworcester** [comment]
An easier way would be to run it with AppImage in [portable mode](https://docs.appimage.org/user-guide/portable-mode.html), which is as simple as creating a directory called `Zbay.AppImage.config` in the same directory as `Zbay.AppImage` and running `Zbay.AppImage`. This will cause that instance of Zbay to use this new directory as its .config.

This gets you two Zbays working great. As long as you make sure to `killall tor` before starting, and let one get up and running before you start the other, it seems to work. 

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/213678/117487543-37da9280-af39-11eb-96c4-87e471e287bc.png">

Here you can see each version of Zbay running its own version of Tor:
```
holmesb+ 1374139  0.2  0.2  32056 23256 ?        Ss   13:12   0:01 /tmp/.mount_Zbay-3391z9E/resources/tor/tor -f /home/holmesbrandnew/zbay2/Zbay-3.2.9-zbay-lite.AppImage.config/Zbay/torrc
holmesb+ 1374921  0.1  0.3  35116 26704 ?        Ss   13:14   0:00 /tmp/.mount_Zbay-3NMq7BW/resources/tor/tor -f /home/holmesbrandnew/.config/Zbay/torrc
```

The problem is, I think they are both connecting to the same SOCKS port. You see this line in both logs:

```
May 07 13:38:24.486 [notice] Opened Socks listener on 127.0.0.1:9050
``` 

So something is off. Perhaps we could have the dev version run the SOCKS proxy on a different port?

**Comment by holmesworcester** [comment]
Okay, I figured this out using Docker on the latest Ubuntu 18. Multiple zbays can run and connect to the Tor network without messing each other up. Issues:

* This will do a fresh install each time, so you'll have to keep it running all the time. We could use `COPY` for this to pull in local Zbay and Zcash directories, if we want to. 
* The windows don't like being resized, at least on my machine. 
* It downloads a fresh version of Zbay each time, from the URL in the Dockerfile. We could also use `COPY` for this with a local Zbay.

Dockerfile:

```
FROM ubuntu:18.04
RUN apt update && apt install curl fuse libnss3 libasound2 libgconf2-4 libnotify4 libnspr4 libnss3 libpcre3 libpulse0 libxss1 libxtst6 libgtk2.0-dev glade -y && curl https://s3.amazonaws.com/release.zbay.lite.waggle/Zbay-3.2.11-zbay-lite.AppImage -o zbay && chmod +x zbay
CMD ["./zbay", "--no-sandbox", "--disable-gpu"]
```

Then...

```
sudo docker run --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --device /dev/fuse --privileged zbay
```

**Comment by holmesworcester** [comment]
@vinkabuki @EmiM @Dinek007 can you all confirm that the above works for you?

**Comment by kowalski** [comment]
The only thing I'm missing here if for the startup command to also care about data-persistance.
For whatever directories that zbay holds data (I know about $HOME/.zbay, @vinkabuki?), we should add to command line:

```
--volume zbay-prod:/root/.zbay
```

This way after the container is removed and added, the account data will be preserved. Otherwise it will be lost with the container

**Comment by holmesworcester** [comment]
Okay, and we might want to have it *not* use the default directory, so that we'll have an account that's never used on the dev version.

**Comment by holmesworcester** [comment]
Noting here: emi says:

> I changed to 3.2.12 in dockerfile for test and now it says that "Gtk-Message: 13:31:32.193: Failed to load module "canberra-gtk-module""

**Comment by holmesworcester** [comment]
UPDATE: The following works on both Ubuntu 18 and 20, fixes the "missing canberra-gtk-module" issue, and it will create a volume so that your identity will persist. 

Remaining issues:
* Resizing the window still breaks the app. 

Dockerfile:

```
FROM ubuntu:18.04
ARG version
RUN apt update \ 
	&& apt install curl \
	fuse \
	libnss3 \
	libasound2 \
	libgconf2-4 \
	libnotify4 \
	libnspr4 \
	libnss3 \
	libpcre3 \
	libpulse0 \
	libxss1 \
	libxtst6 \
	libgtk2.0-dev \
        libgconf-2-4 \
	glade \
	libcanberra-gtk-module \
	libcanberra-gtk3-module \
	-y \
	&& curl https://s3.amazonaws.com/release.zbay.lite.waggle/Zbay-${version}-zbay-lite.AppImage -o zbay \ 
	&& chmod +x zbay
CMD ["./zbay", "--no-sandbox", "--disable-gpu"]
```

Then...

```
sudo docker build --build-arg version=VERSION -t zbay .
```

Where VERSION is the version number, i.e. 3.2.13 and...

```
xhost local:root && sudo docker run --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --device /dev/fuse --privileged zbay
```

This will let you run Zbay in Docker, alongside a locally-running Zbay.

**Comment by EmiM** [comment]
**Note**: when I use Ubuntu 20.04, I get the information that `E: Package 'libgconf2-4' has no installation candidate`.
Using libgconf-2-4 solves the problem.

**Comment by holmesworcester** [comment]
> Using libgconf-2-4 solves the problem.

Added above.
