### ISSUE TITLE
User should see a loading indicator until waggle is synced and ready to send

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#778]
Sometimes we see an issue (#776) where Waggle takes a long time to sync on restart. 

When this is happening, the user should:

1. not have their messages fail silently. 
2. know that they are not seeing all messages yet.

I'm agnostic on the best way to achieve this, but I want to discuss it a bit and make sure that whatever we decide to do is something we'll be okay with living with for a while.

**Comment by holmesworcester** [comment]
Here's a rough mockup of what it could look like.

**Note:** it may be better to put the message *underneath* the text entry field, the way we currently do for typing indicators. The advantage of doing it this way would be that we already have design for text that displays there. (I'm not sure we have any design for a temporary message that appears *above* the text entry field.

![image](https://user-images.githubusercontent.com/213678/116081996-e690f000-a668-11eb-9d23-3a36979d3714.png)

**Comment by holmesworcester** [comment]
@vinkabuki is this done in the release with DMs?

**Comment by holmesworcester** [comment]
Also, I think we should probably use the existing design for typing indicators, rather than improvising new design.

If there's a spinner icon we can add, that's even better. 

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/213678/116414777-c434d900-a806-11eb-86b5-e8f13498d5ad.png">

**Comment by holmesworcester** [comment]
@vinkabuki I think it was good to add this indicator here, but I don't think the current behavior is clear enough to release.

Right now you see this warning, which refers to "waggle" (something the user doesn't know about) and isn't clear.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/213678/117310563-62512080-ae51-11eb-842e-9255893c9fd7.png">

Then if you try to send a message it disappears. 

Then if you try to send another message it doesn't let you send it and enter does nothing.

**Comment by holmesworcester** [comment]
I think the quickest route on this is to grey out the field and use something like our "____ is typing..." text below the field to show the message above. 

But the ideal solution would be to let the user send the message, and show some indicator that it is sending.

**Comment by vinkabuki** [comment]
Ideal solution needs separate task: https://github.com/ZbayApp/zbay/issues/810

**Comment by holmesworcester** [comment]
@vinkabuki as long as we grey out the field while the loading indicator is happening, that's fine. we don't need to queue.
