### ISSUE TITLE
do not use separete components for direct messages

### ISSUE THREAD

**Issue by vinkabuki** [ZbayApp/zbay#794]
We have two separate components for DM and public channels, when you switching between them there is a lag

**Comment by holmesworcester** [comment]
@vinkabuki what's the difficulty/impact ratio for this one, compared to other performance issues?

**Comment by vinkabuki** [comment]
I'd say time estimate for this is 2-3 points, impact ratio is not horrible (or we used to it), my main concern is that it yields other small bugs, where we already spent 4-5 points, because solutions are not obvious and we must use 'hacks'. I think it is better to fix this now, otherwise I'm 99% sure it will give us bugs again and again and we will be wasting time on fixing them, not tackling the root cause

**Comment by holmesworcester** [comment]
Okay, I’m good with doing it now!
