### ISSUE TITLE
Message input field "loses" the first character of user's message

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#799]
steps to reproduce in 3.2.11:

1. switch to channel
2. click in message input field
3. type "tangle"

expected: message input field shows "tangle"
actual: message input field shows "angle"

**UPDATE:** at some point this stopped happening, so it might be intermittent.

**Comment by vinkabuki** [comment]
can't reproduce atm

**Comment by holmesworcester** [comment]
I've seen it on first run, perhaps before waggle is connected. I don't have exact steps to reproduce yet though.

**Comment by vinkabuki** [comment]
I think it is another child of https://github.com/ZbayApp/zbay/issues/794
