### ISSUE TITLE
DM conversation with "holmes" still shows "you are not fully synced..." alert even when zbay channel is working.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#800]
Steps to reproduce in 3.2.11:

1. Start zbay
2. Switch to #zbay channel
3. Wait for "You are not fully synced with waggle, it may take few minutes" message to go away.
4. Switch to conversation with holmes

Expected: "You are not fully synced..." message is not visible, since it's not visible in the other chat.

Actual: still visible.

**Comment by vinkabuki** [comment]
That's expected behavior, because homes has no waggle identity probably, but the message should be different, changing this now to "the user you are trying send message to hasn't joined p2p network yet". Is that ok?

**Comment by holmesworcester** [comment]
I remember suggesting draft text in Slack but can't find it. :/ This will do:

"To receive direct messages, holmes must update to the latest version of Zbay."
