### ISSUE TITLE
User holmes cannot receive messages from other users

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#805]
Steps to reproduce:

0. Verify that holmes is signed in and can send messages to the zbay channel
1. Send message to holmes.

Expected: received
Actual: nothing received.

**Comment by holmesworcester** [comment]
This appears to be fixed. I have an issue where messages don't load until i send, and another issue where (as a result of the first issue, I think) I don't see notifications or any indication that there are new messages. But I can see them eventually.

**Comment by kingalg** [comment]
This may be fixed but we don't have a way to check this in version 3.2.14 as there are waggle problems. To be moved to "ready for qa" with general waggle fix.

**Comment by kingalg** [comment]
Moved back as per comment from an hour ago.
