### ISSUE TITLE
Can't close zbay 

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#820]
I can't close zBay on MacOS - **using "x"** is only minimising app to the menu bar (it is actually how it is working on Mac with apps but it was decided that we want zbay to close completely on "x" and it worked in a few previous versions. 
**Using "Quit"** from menu bar - does nothing.
**Using "Quit zbay"** from menu at the top of the page - does nothing
Restarting computer doesn't solve this issue.
Only **using "force quit"** is working.

For Windows - my zbay on windows can be closed without any process hanging but I've know that there are users that can't close zbay on Windows.

![Screenshot 2021-05-11 at 14 12 45](https://user-images.githubusercontent.com/68909168/117813095-f6145980-b262-11eb-90e4-913929790c65.png)
![Screenshot 2021-05-11 at 14 12 58](https://user-images.githubusercontent.com/68909168/117813123-fe6c9480-b262-11eb-9083-b488f02aca50.png)
![Screenshot 2021-05-11 at 14 13 58](https://user-images.githubusercontent.com/68909168/117813252-222fda80-b263-11eb-8feb-37da0674319d.png)

**Comment by holmesworcester** [comment]
Notes:

When I close the window using the red X button in the top left corner in Mac, Zbay fails to quit. Once doing it I also got a js error, though this does not always happen. 

```
Uncaught Exception:
Error: ENOENT: no such file or directory, stat '/Users/holmes/Library/Application Support/Zbay/ZbayChannels/repo.lock'
```

The behavior is similar to the behaviorwe saw a while ago on window close where waggle doesn't restart, and Zbay is in a "connecting" state where messages can't be sent or received.

> Using "Quit" from menu bar - does nothing.

I can't reproduce this. I *can* reproduce the behavior where Zbay stops working properly after closing the window and reopening it. 

**UPDATE:** I can reproduce this in the Zbay release candidate 3.2.13, but not in develop. I can even build a Zbay.app from develop and not reproduce this. @vinkabuki what's going on here? Are builds happening from a branch other than develop?? What else could it be?

**Comment by kingalg** [comment]
Looks like this issue has been resolved.
