### ISSUE TITLE
@mentions don't work on mac

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#833]
Steps to reproduce:

1. Start Zbay mac 3.2.14
2. Type "@" in message field

Expected: Message popper for selecting user to @ mention should display. 

Actual: It doesn't.

**Comment by kingalg** [comment]
Still a but in 3.2.20 on both Mac and Windows.

**Comment by holmesworcester** [comment]
duplicate of https://github.com/ZbayApp/ZbayLite/issues/314
