### ISSUE TITLE
Notifications keep triggering again for the same message.

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#836]
Notifications keep triggering again for the same message. They are on the loop.

Systems: Windows, MacOS

Version: 3.2.14

**Comment by vinkabuki** [comment]
should be solved automatically after refactoring waggle-zbay

**Comment by holmesworcester** [comment]
we think this is fixed but need to check

**Comment by holmesworcester** [comment]
@vinkabuki are there tests for this?

**Comment by kingalg** [comment]
It's done.

**Comment by vinkabuki** [comment]
There are no tests for functions related to notifications. There are two parts for this - one for testing notification functions themselves, and second for testing if sagas triggering notifications correctly
