### ISSUE TITLE
User should be able to register an account with new orbitdb identity scheme

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#853]
requirements:

- if username is taken, api should respond with an error and client should say that the username is taken.
- if username is not taken, it provides a certificate and updates the orbitdb username/key table

**Comment by EmiM** [comment]
Server part is ready: https://github.com/ZbayApp/waggle/pull/57 
Not wunning on aws yet. ZbayLite part (communication with the server) will be implemented in separate task: https://github.com/ZbayApp/ZbayLite/issues/296
