### ISSUE TITLE
Channel participant count sits at 0 until posting first message

### ISSUE THREAD

**Issue by BostonZcash** [ZbayApp/zbay#97]
**Version:** 1.0.66-dev-linux-18-2 (appimage)

In either creating a channel or joining an (ostensibly empty) existing one, the channel participant count sits at `0 Participants` until one posts their first message within it.

This wasn't true for the already populated `#zbay` channel, though it did have me wondering whether I had successfully created and made public a new room.

**Comment by holmesworcester** [comment]
duplicate of #119 (moving internal tickets to github now)
